### ISSUE TITLE
CSS formatting error with one or two pseudo classes

### ISSUE THREAD

**Issue by vallieres** [akalongman/sublimetext-codeformatter#100]
When formatting the CSS code and an element has one or two pseudo-classes, it introduces an extra space and breaks the CSS.

**Single pseudo-class**

    #top_menu ul li.spectacle:last-child {
        margin-right: 40px;
    }

Becomes this after Format Code is ran:

    #top_menu ul li.spectacle: last-child {
        margin-right: 40px;
    }

**Double pseudo-class**

    #connexion ul li:last-child:after {
        content: "";
    }

    #connexion ul li: last-child:after {
        content: "";
    }

Thanks!

**Comment by akalongman** [comment]
Fixed in 2.6.0 version
