### ISSUE TITLE
Make css formatting work with .less files

### ISSUE THREAD

**Issue by muluc** [akalongman/sublimetext-codeformatter#103]
Hey thank you for your great work on that... it would be nice if you could enable .less file extension for css formatting or profile the option to define file extension matchers

cheers

Florian

**Comment by steffenr** [comment]
I also tried auto-formatting and get the same issue as @muluc ;(

´´´
.links-wrapper {
        clear: both;
        margin: 0;
        ul {
            &.links {
                display: block;
                margin: 0;
                padding: 0;
                li {
                    display: block;
                    margin: @grid-gutter-size / 2 0 0;
                    padding: 0;
                    white-space: nowrap;
                    a {
                        .bi-button();
                        display: block;
                   }
              }
         }
    }
}
}
}
```

**Comment by noducks** [comment]
Am having the same issue. 

Below is the output I get from codeformatter.

     .test {
         cursor: pointer;
         .btn {
             height: 50px;
             &:hover {
                 background-color: #f5f5f5;
            }
            .top {
                font-size: 15px;
           }
           .bottom {
               font-size: 9px;
          }
     }
     }

If I format with js-beautify directly. 

     $ js-beautify -v
     1.5.4
     $ js-beautify --type css test.less

The output is well formed. May just need a version update.

     .test {
         cursor: pointer;
         .btn {
             height: 50px;
             &:hover {
                 background-color: #f5f5f5;
             }
             .top {
                 font-size: 15px;
             }
             .bottom {
                 font-size: 9px;
             }
         }
     }

**Comment by noducks** [comment]
As a temporary fix. 

     git clone https://github.com/beautify-web/js-beautify.git

Replace the old cloned cssbeautifier folder here:

    ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/CodeFormatter/codeformatter/lib/cssbeautifier 

with the new cloned one here:

     js-beautify/python/cssbeautifier

And all works as expected... so far.
