### ISSUE TITLE
Error while trying to format

### ISSUE THREAD

**Issue by RedLann** [akalongman/sublimetext-codeformatter#109]
i get an error on sublime text 3 that says:
Code Formatter

Format error:
[Errno 32] Broken Pipe

and nothing gets formatted.

**Comment by crsjerry** [comment]
Windows 7 PHP Formatter

**Comment by rvkennedy** [comment]
I have the same on Windows 8.1, PHP formatter, Sublime Text 3

**Comment by akalongman** [comment]
Fixed in 1.6.1 version
