### ISSUE TITLE
CSS: Space entered between double colon (::)

### ISSUE THREAD

**Issue by RUMPIKUF** [akalongman/sublimetext-codeformatter#117]
When CSS is formatted, a space is placed between the two colons.
Example:
<code>a::after</code>
becomes
<code>a: :after</code>
which does not work in the same way as without the spaces.

**Comment by pristavu** [comment]
https://github.com/akalongman/sublimetext-codeformatter/blob/master/codeformatter/lib/cssbeautifier/__init__.py#L162

self.pseudo_classes = ["link", "visited", "active", "hover", "focus", "first-letter", "first-line", "first-child", "before", "after", "lang", "language",":-",":-moz",":-webkit",":-ms"]

**Comment by akalongman** [comment]
Can you send me pull request?

**Comment by akalongman** [comment]
Fixed in 2.6.0 version
