### ISSUE TITLE
Space before conditional

### ISSUE THREAD

**Issue by delyan-georgiev** [akalongman/sublimetext-codeformatter#120]
Hi, your plugin is very useful for me and my team, but can you add "sapce_before_conditional" option, because only  this is  missing in this great plugin !

Thanks for your work.

**Comment by akalongman** [comment]
In which formatter?

**Comment by delyan-georgiev** [comment]
php and js

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
