### ISSUE TITLE
"end_with_newline": true does not work for js files

### ISSUE THREAD

**Issue by OrKoN** [akalongman/sublimetext-codeformatter#121]
I need to keep the newline in the end of the js file. Is this supported?

**Comment by mtpultz** [comment]
It appears to not be supported yet.  A list of unsupported JS formatting compared to another package like HTML/CSS/JS Beautify appears to be:

* end_with_newline
* indent_level
* space_after_anon_function
* space_before_conditional
* space_in_empty_paren
