### ISSUE TITLE
PHP setting to allow/prevent single line statements with/out brackets

### ISSUE THREAD

**Issue by mtpultz** [akalongman/sublimetext-codeformatter#126]
Feature Request:

A setting to either allow single like statements:
```php
if (Auth::check()) return Redirect::to('dashboard');
```
Or format them so they use brackets:
```php
if (Auth::check()) 
{
    return Redirect::to('dashboard');
}
```

**Comment by TemaSM** [comment]
Yep! Really needed. Very often using same code while coding with Laravel.

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
