### ISSUE TITLE
Compatibility with other 'file types' - e.g. Javascript Next

### ISSUE THREAD

**Issue by dsl101** [akalongman/sublimetext-codeformatter#127]
I'm using an alternative JS syntax highlighting package ([Javascript Next](https://packagecontrol.io/packages/JavaScriptNext%20-%20ES6%20Syntax)) which I prefer over the plain Javascript syntax. However, I can't get Code Formatter to run without first changing the syntax back. It throws an error "Formatter for this file type (javacsriptnext - es6 syntax) not found.

I don't need a whole new formatter - just to call the Javascript one from a different syntax setting. I couldn't see a way of doing that in the settings file - or maybe I just didn't follow it properly. Is it possible to include a list of syntax settings for which each formatter is 'valid', so that I can save several clicks each time?

**Comment by jameskopacz** [comment]
I have the same issue with [JavaScript Ultimate](https://packagecontrol.io/packages/JavaScript%20Ultimate).
I was able to get it working by editing: ```Packages/CodeFormatter/codeformatter/formatter.py``` and adding "javascript ultimate" (the formatter that wasn't found) to the [classmap object on line 34](https://github.com/akalongman/sublimetext-codeformatter/blob/master/codeformatter/formatter.py#L34).

For me it looks like this now:
```python
		self.classmap = {
			'php': PhpFormatter,
			'javascript': JsFormatter,
            'javascript ultimate': JsFormatter,
			'json': JsFormatter,
			'html': HtmlFormatter,
			'asp': HtmlFormatter,
			'xml': HtmlFormatter,
			'css': CssFormatter,
			'less': CssFormatter,
			'python': PyFormatter
		}
```

**Comment by thecotne** [comment]
you can use command palette to run `CodeFormatter: Format as Javascript Syntax`
or wait for next release where syntaxes option added https://github.com/akalongman/sublimetext-codeformatter/blob/master/CodeFormatter.sublime-settings#L34

**Comment by PavelPolyakov** [comment]
@thecotne 

Hi, 

I have the next in my configuration:
![image](https://cloud.githubusercontent.com/assets/839290/11165930/a050f0d2-8b1f-11e5-8ab8-9a0ae6fc124a.png)

However, when I try to format the file, I have the next alert:
![image](https://cloud.githubusercontent.com/assets/839290/11165932/b06b5a48-8b1f-11e5-9ba8-95caa2dbc13d.png)

Is that normal?
How can I configure the plugin to format javascriptnext? I saw the file you are referring, however I hadn't had such configuration option in my config. I have added it, but do not see any effect.

Regards,

**Comment by thecotne** [comment]
@akalongman why last release version is so old? 10 commits behind master

@PavelPolyakov i was thinking it was released but it is not

**Comment by akalongman** [comment]
@thecotne Will be released today

**Comment by PavelPolyakov** [comment]
@thecotne @akalongman 
As I understand, nothing was released for now? :(

https://github.com/akalongman/sublimetext-codeformatter/releases

Regards,

**Comment by magleahy** [comment]
What's the update on this?
I am having the problem for all CodeFormatter on Sublime Text 3. 
It used to work and broke sometime in the last 3 months perhaps?
