### ISSUE TITLE
New Install and "'php' is not recognized as an internal or external command"

### ISSUE THREAD

**Issue by sodacrackers** [akalongman/sublimetext-codeformatter#129]
On trying the package I see a "no PHP" error although I'm running PHP 5.x fast-cgi.  It's available in cygwin.....  Any recommendations here? 

```
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
ignored packages updated to: [Vintage]
found 1 files for base name Default.sublime-theme
reloading Packages/User/Package Control.sublime-settings
theme loaded
reloading plugin CodeFormatter.CodeFormatter
CodeFormatter: formatting python files on ST3 not supported.
CodeFormatter: Plugin Initialized
found 8 files for base name Default.sublime-keymap
found 7 files for base name Main.sublime-menu
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
error: CodeFormatter

Format error:
'php' is not recognized as an internal or external command,
operable program or batch file.



number of files to index exceeds sanity limit, bailing out
```

![screenshot 2015-01-20 18 58 58](https://cloud.githubusercontent.com/assets/1248488/5830502/6eb20536-a0d6-11e4-8353-ed83321bf859.png)

**Comment by akalongman** [comment]
You must specify php path in settings or add it in system PATH environment

**Comment by 2096hamid** [comment]
how i specify php path in settings?

**Comment by akalongman** [comment]
See example in default settings file

**Comment by chintanpanchal01** [comment]
Have you setup your PHP path in system environment variable. Please take a look this tutorial 
[http://www.codeandtuts.com/solved-php-is-not-recognized-as-an-internal-or-external-command](http://www.codeandtuts.com/solved-php-is-not-recognized-as-an-internal-or-external-command/)
