### ISSUE TITLE
else goto new line for "k&r" indent_style

### ISSUE THREAD

**Issue by n00bik** [akalongman/sublimetext-codeformatter#133]
i.e. was before
if ($attempt++ > 5) {
  die("\t\t\terror : max attempt limit reached.\n");
} else {
  $sleep_time+= $sleep_time;
  MyEcho("curl again after $sleep_time sec's.");
}

and now

if ($attempt++ > 5) {
  die("\t\t\terror : max attempt limit reached.\n");
} 
  else {
  $sleep_time+= $sleep_time;
 MyEcho("curl again after $sleep_time sec's.");
}

**Comment by CodyPChristian** [comment]
Any update to this? Its aggravating to me and also PHPBeautifier itself does not break them onto separate lines. Anyone know what file/line is doing this within the plugin?

**Comment by rtorcato** [comment]
my else statements look so weird. need a fix for this, but great plugin everything else looks great.

**Comment by cigzigwon** [comment]
confirmed, also class gets newline even if set to false... this happened after I recompiled PHP on another machine

**Comment by jsabino** [comment]
This issue is caused by the commit c407cc5f10

**Comment by cigzigwon** [comment]
can we get this ?
obviously the hack to fix is...
<code>if (strtolower($this->getSetting('style')) == 'allman') { $this->oBeaut->addNewLineIndent(); }</code>

what it should of been since his fix broke k&r!

**Comment by akalongman** [comment]
Send me pull request and I will merge it

**Comment by cigzigwon** [comment]
After the fix is applied don't forget to set pear to false because pear defaults to allman for else statements.

**Comment by cigzigwon** [comment]
Is my P.R. ever going to get merged? I updated meh box today stuck with this issue again. Pear is off and else still get shoved to new lines it needs the patch.

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
