### ISSUE TITLE
Feature request: keep_multiple_variable_indentation

### ISSUE THREAD

**Issue by renarsvilnis** [akalongman/sublimetext-codeformatter#135]
Hi, i have a feature request, i would like an option to preserve indentation when initializing multiple variables within javascript.

```javascript
var x = head.x,
    y = head.y;
```
After formating i would like to preserve indentation shown above.

```javascript
var x = head.x,
  y = head.y;
```
For now it gets formatted to the above.

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
