### ISSUE TITLE
Indention added between class functions

### ISSUE THREAD

**Issue by Nique** [akalongman/sublimetext-codeformatter#141]
Hello, 

Currently there will be added some indentions in between of the functions within classes. This is kinda annoying because i want to trim all white spaces at the end of a line.

Is there a way to trim white spaces at line endings?

**Comment by thecotne** [comment]
@Nique can you give us example file
i can't reproduce issue since you even not mentioned in which language you have issue

**Comment by Nique** [comment]
Oh wow, that's a long time ago. I can't remember but I think it was in PHP. If it still bugs me i'll send you a better issue report. I don't even know anymore what i meant with the line-endings. Sorry, i think that part of my memory has been overwritten by memories of a gorgious girl on the beach last summer :).

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
