### ISSUE TITLE
Fix st3 3088 not working

### ISSUE THREAD

**Issue by momoca** [akalongman/sublimetext-codeformatter#145]
https://github.com/akalongman/sublimetext-codeformatter/blob/master/codeformatter/formatter.py#L84

pattern = re.compile(r"Packages/(.+?)/.+?\.tmLanguage")
Replace
pattern = re.compile(r"Packages/.*/(.+?)\.(?=tmLanguage|sublime-syntax)")

**Comment by akalongman** [comment]
@momoca fixed. Thank you!
