### ISSUE TITLE
PHP glue-amperscore setting

### ISSUE THREAD

**Issue by rickysullivan** [akalongman/sublimetext-codeformatter#149]
Is there a setting like this?

With --glue-amperscore
```
<?php

$value = &$objectInstance;

?>
```

Without --glue-amperscore
```
<?php

$value = & $objectInstance;

?>
```

Taken from: http://www.waterproof.fr/products/phpCodeBeautifier/manual.php

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
