### ISSUE TITLE
js code formatter not work under windows 7

### ISSUE THREAD

**Issue by hxshandle** [akalongman/sublimetext-codeformatter#153]
Now I met a problem that js code formatter not work for me on windows 7, I got the following error message.
```
Format error:
No module named 'jsbeautifier.six'
error: CodeFormatter
```

I tried to reinstall the plugin but not worked.

PS: codeFormatter works fine on my MAC.

**Comment by thecotne** [comment]
@hxshandle did new version fixed this?

**Comment by hxshandle** [comment]
@thecotne The new version fixed, thanks.

**Comment by AjiMIde** [comment]
I get the same problem when i use 'ctrl+alt+F' to format my 'css' file. it tips me the msg : 
`
No module named 'jsbeautifier.six'
`
I have tried to reinstall the plugin but not worked.
My environment is st3 and win10.
