### ISSUE TITLE
filter for late static bindings

### ISSUE THREAD

**Issue by cigzigwon** [akalongman/sublimetext-codeformatter#158]
Static is not always a keyword. I'm very particular. And late static bindings should be skipped somehow...
"static ::MANUAL_ID" should not get a space

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
