### ISSUE TITLE
New lane after <?php

### ISSUE THREAD

**Issue by leministreMichael** [akalongman/sublimetext-codeformatter#159]
Greetings!

I really love your plugin. But I've no idea how to make it do a new lane after <?php
I've tried to edit options this way:
		"new_line_after": "<?php"
But it didn't work for me.

It would be great if you could suggest a solution! Thanks beforehand.
______________________________________________________
P.s. I need my code to be formatted as this
<?php

$start = ".....";...

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
