### ISSUE TITLE
[ BUG ] [ JS ] [ ST3 ] Comma-first formatting support disabled?

### ISSUE THREAD

**Issue by clemeno** [akalongman/sublimetext-codeformatter#160]
Comma-first feature
---
Some weeks ago appeared the `"comma_first": true // Add comma first` option for javascript formatting which was a very convenient syntax for the variable declaration section, but seems to be disabled now. Turning it from false to true in the configuration has no effect. Was it just experimental & temporary? It would be great if the feature came back, it seems I'm not the only one on Github who likes this style. 

Example
---
Code formatted comma-first with k&r, 2 space, space between !empty paren & square, ';' at 'var' level and object attributes aligned: 

```javascript
var a = 1
  , b = 'a'
  , c = {
      c_a: 2
    , c_b: 'b'
  }
  , d = [
    {
        'd1 a': 3
      , 'd1-b': 'c'
    }
    , {
        d2_a: 4
      , d2_b: 'd'
    }
  ]
  , e = [ 5, 6, 7, 8, 9 ]
  , f = function( x, y ) {
    return !( ( x - y ) % 2 )
  }
;
console.log( f( c.c_a, d[ 1 ].d2_a ) )
```

**Comment by akalongman** [comment]
Why you close issue?

**Comment by clemeno** [comment]
I don't know why this feature did not worked as expected when I tried it two weeks ago (possibly linked to a weird update from `Package Controll`), but I had the occasion to make some tests recently on the same files, same project, and this comma-first feature was working again. 

So this is not an issue anymore: `"comma_first": true` enables the feature as expected now.

**Comment by akalongman** [comment]
Ok. Thank you for support

**Comment by cchamberlain** [comment]
@akalongman This plugin is great, however I prefer no newline following the open bracket or curly on arrays and object literals.  My style is like so (things line up better).  Any ability to add support so the first line doesn't get a new line?  Doesn't have to be exact, just something more along the lines of https://gist.github.com/isaacs/357981.

```js
var a = 1
  , b = 'a'
  , c = { c_a: 2
        , c_b: 'b'
        }
  , d = [ { 'd1 a': 3
          , 'd1-b': 'c'
          }
        , { d2_a: 4
          , d2_b: 'd'
          }
        ]
  , e = [ 5, 6, 7, 8, 9 ]
  , f = function( x, y ) { return !( ( x - y ) % 2 ) }
```

**Comment by cchamberlain** [comment]
Seems like this will require upstream support so I've commented on issue https://github.com/beautify-web/js-beautify/issues/743 in js-beautify.
