### ISSUE TITLE
Making your own custom/additional options (PHP)

### ISSUE THREAD

**Issue by brettalton** [akalongman/sublimetext-codeformatter#163]
I have two sort of odd code formatting practices and I was wondering if I could modify this script to support them.

```
// Do magic
//
include( 'inc/do-magic.php' );
```

The first is that I add newline of padding inbetween my comments and the line it's speaking to. They're connected via an empty comment. This gives the comment and code room to breath but with the visual cue they're connected. Do you think there is any way of adding this?

```
// Do something crazy
//
if ( ! in_array_ci( $needle, $haystack ) )
```
One other thing I do is pad exclamation marks. I need to do this visually as I find their use important and giving them a space allows me to see the important NOT operator.

If someone can point me in the right direction for these two modifications, it would be greatly appreciated. Thank you.

**Comment by jakebathman** [comment]
Definitely interested in doing the same thing (but different modifications). I'm going to dive into the source and see if I can get some of them to work. Let me know if you get yours going.

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [release notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
