### ISSUE TITLE
Nothing happens after typing [Format Code]

### ISSUE THREAD

**Issue by aaronliruns** [akalongman/sublimetext-codeformatter#165]
The package control message would indicate success installation of code formatter on ST3 3083 (Mac).
However, when I try to type Format Code in Command Palette the auto complete function doesn't run and there is just nothing happens when I entered the entire Format Code command. I don't think this is a bug but pointers on how to debug and fix it are highly appreciated.

Aaron
<img width="1190" alt="screen shot 2015-10-02 at 1 31 03 pm" src="https://cloud.githubusercontent.com/assets/14796538/10240120/853bb5ca-690a-11e5-87da-b5262cd98af7.png">

**Comment by akalongman** [comment]
Look at sublime console after editor starts. Probably you have error in plugin. You must check error in console (super+`)

**Comment by raphahardt** [comment]
I've got the same issue, and the console output is this:

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
  File ".\CodeFormatter.py", line 73, in run
  File ".\codeformatter\formatter.py", line 74, in format
  File ".\codeformatter\formatter.py", line 95, in clean
  File ".\encodings\utf_8.py", line 16, in decode
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 1652: ordinal not in range(128)

**Comment by oldoni** [comment]
I have the same problem but in the console do not have any error message  

DPI scale: 1
startup, version: 3083 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/marcelo/.config/sublime-text-3/Packages
state path: /home/marcelo/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/marcelo/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.243592
startup time: 0.37349
first paint time: 0.376075
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Emmet.emmet-plugin
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin CodeFormatter.CodeFormatter
CodeFormatter: formatting python files on ST3 not supported.
reloading plugin emmet-sublime-master.emmet-plugin
plugins loaded
CodeFormatter: Plugin Initialized
PyV8: Creating new thread
Emmet: Creating thread
Emmet: No need to update PyV8
Emmet: Loading https://api.github.com/repos/emmetio/pyv8-binaries/contents
Emmet: Loading PyV8 binary from https://raw.github.com/emmetio/pyv8-binaries/master/pyv8-linux64-p3.zip
Package Control: Skipping automatic upgrade, last run at 2015-10-07 16:21:02, next run at 2015-10-07 17:21:02 or after

**Comment by ciadavid** [comment]
Me too, plugin is not working... and console log dont see errors

**Comment by dharmendrajadon** [comment]
Any solution yet? Its working on windows and not on mac! Any solution for mac?

**Comment by akalongman** [comment]
Please, provide example file

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
