### ISSUE TITLE
CSS Format issues with pseudo selector

### ISSUE THREAD

**Issue by vedran314** [akalongman/sublimetext-codeformatter#167]
Hi there are some issues when using codeformatter on CSS.

Codeformatter adds spacing between colon and classname.

![format-error](https://cloud.githubusercontent.com/assets/4938223/10515049/d1f75f9e-7351-11e5-88c9-6b08300f59c2.png)

**Comment by thecotne** [comment]
can't reproduce with latest version on fedora linux with ST 3083
it can be platform specific @vedran314

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
