### ISSUE TITLE
Coldfusion codeformatter

### ISSUE THREAD

**Issue by davidetamburini** [akalongman/sublimetext-codeformatter#168]
![senza-titolo-1](https://cloud.githubusercontent.com/assets/517971/10659165/0f6d92ac-789e-11e5-977c-339e62e8afda.jpg)
When I try to use codeformatter on a *.cfm or *.cfc file I receive an error (see attached image).
Is it possibile to add rules for type file coldfusion?

**Comment by thecotne** [comment]
#114

**Comment by thecotne** [comment]
@davidetamburini i don't know when this going to be merged
