### ISSUE TITLE
newline_before_comment

### ISSUE THREAD

**Issue by interchen** [akalongman/sublimetext-codeformatter#169]
```
define("KEY", value); \\ this is comment
```
if newline_before_comment is true, the code will be formatted to 
```
define("KEY", value);
\\ this is comment
```
I don't want a new line like this. How can I formatter my code with "newline_before_comment" option is true?

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
