### ISSUE TITLE
formatting HTML + PHP repeatedly adds extra spacing to closing brackets

### ISSUE THREAD

**Issue by 01271** [akalongman/sublimetext-codeformatter#172]
With the following code in the php formatter, the ending closing bracket gets pushed back one tab every time.

<?php function site_header(){
$site_description = '';
$site_keywords = '';
$page_title = '';
$site_icon = '';?>
<!DOCTYPE HTML><html lang="en"><head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="description" content="<?php echo $site_description ?>" />
    <meta name="keywords" content="<?php echo $site_keywords ?>" />
    <link href=media/img/icon/<?php echo $site_icon ?> rel=icon>
        <title><?php echo $page_title?></title>
        <link href="css/structure.css" rel="stylesheet" type="text/css">
    </head>
    <body>
    <header>This is the site header</header> <?php
}
A-- This closing bracket.
To reproduce this bug simply format this code over and over.

**Comment by 01271** [comment]
This is with inconsistent use of tabs, with 
	"codeformatter_php_options":
	{
		"indent_with_tabs": true, // Indent with tabs or spaces

and 
	"codeformatter_html_options":
	{
		"indent_with_tabs": true, // Indent with one tab (overrides indent_size and indent_char options)

With them both the same, the result is that it only does it once

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
