### ISSUE TITLE
It stopped working

### ISSUE THREAD

**Issue by EdwinPalacios** [akalongman/sublimetext-codeformatter#173]
I need help!!

I stopped running the plugin and change settings and PHP.

{
     "codeformatter_php_options": {
           "php_path": "C:/xampp/php/php.exe"
      }
}

although this PHP environment variables.

Error:
![captura de pantalla 1](https://cloud.githubusercontent.com/assets/8704016/12423839/7173c7a8-be9b-11e5-8fa2-01314dd89aec.png)

**Comment by holgerh** [comment]
I have the same problem since today for javascript

**Comment by akalongman** [comment]
I will fix it asap

**Comment by EdwinPalacios** [comment]
Thank you very much will be careful.

**Comment by jakebathman** [comment]
Make sure you go update your user settings file after this package is updated. Mine was using the pre-3.0 settings file, which the 3.0 version wasn't using properly. Copy the new default settings file over and re-do your settings, **including adding your path to PHP** in the new user settings file.

**Comment by akalongman** [comment]
@EdwinPalacios @holgerh I've tested on Windows 7 x64 and plugin works fine. Can you show me your config file?

**Comment by Cardinal90** [comment]
Had the same problem for javascript. Copying new default settings into my user settings fixed it.

**Comment by Cardinal90** [comment]
Had the same problem for javascript. Copying new default settings into my user settings fixed it.

**Comment by EdwinPalacios** [comment]
I have Windows 10 pro 64 bits
![captura de pantalla 3](https://cloud.githubusercontent.com/assets/8704016/12449830/f3c18f9e-bf4d-11e5-89a5-ab675ced217f.png)

**Comment by joshwyrick** [comment]
Removing (or commenting out) User settings fixes the problem for me.
(Preferences > Package Settings > CodeFormatter > Settings - User)

**Comment by holgerh** [comment]
works not for me, too :-)

**Comment by akalongman** [comment]
What is final decision? Works or not?

**Comment by holgerh** [comment]
works for me after deleting my old user-settings

**Comment by 01271** [comment]
On OSX El Capitan PHP formatting doesn't work anymore. I've tried setting my path to many of my php locations but it doesn't do anything. I currently have two php 5.6 versions installed but I use my homebrew one because it updates itself easily.
When I do "which php" I get my homebrew php path and when I do php -v I get 
php -v
PHP 5.6.0RC2 (cli) (built: Jul 31 2014 19:31:51) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0-dev, Copyright (c) 1998-2014 Zend Technologies

**Comment by akalongman** [comment]
@01271 what is result of ```which php``` command?

**Comment by swedkg** [comment]
"Removing (or commenting out) User settings fixes the problem for me."
this worked for me too

**Comment by akalongman** [comment]
@01271 try "Removing (or commenting out) User settings fixes the problem for me."

**Comment by EdwinPalacios** [comment]
with the command that is my result. and I tried it on my other pc pro with Windows 10 and 64 bits nor php 7.0.1

which php
/c/xampp/php/php

**Comment by 01271** [comment]
My user settings file is completely blank, there's nothing in it.

**Comment by akalongman** [comment]
Copy content from default setrings file

**Comment by 01271** [comment]
Still unresolved, all my settings have been copy pasted and no change.

here are my preferences
{
    "codeformatter_php_options": {
        "syntaxes": "php", // Syntax names which must process PHP formatter
        "php_path": "/usr/local/opt/php56/bin/php",
        "format_on_save": false, // Format on save
        "psr1": false, // Activate PSR1 style
        "psr1_naming": false, // Activate PSR1 style - Section 3 and 4.3 - Class and method names case
        "psr2": true, // Activate PSR2 style
        "indent_with_space": 4, // Use spaces instead of tabs for indentation
        "enable_auto_align": true, // Enable auto align of = and =>
        "visibility_order": true, // Fixes visibiliy order for method in classes - PSR-2 4.2
        "smart_linebreak_after_curly": true, // Convert multistatement blocks into multiline blocks
        // Enable specific transnformations. Example: ["ConvertOpenTagWithEcho", "PrettyPrintDocBlocks"]
        // You can list all available transnformations from command palette: CodeFormatter: Show PHP Transformations
        "passes": [],
        // Disable specific transnformations
        "exclude": []
    },
    "codeformatter_js_options": {
        "syntaxes": "javascript,json", // Syntax names which must process JS formatter
        "format_on_save": false, // Format on save
        "indent_size": 4, // indentation size
        "indent_char": " ", // Indent character
        "indent_with_tabs": false, // Indent with one tab (overrides indent_size and indent_char options)
        "eol": "\n", // EOL symbol
        "preserve_newlines": false, // whether existing line breaks should be preserved,
        "max_preserve_newlines": 10, // maximum number of line breaks to be preserved in one chunk
        "space_in_paren": false, // Add padding spaces within paren, ie. f( a, b )
        "space_in_empty_paren": false, // Add padding spaces within paren if parent empty, ie. f(  )
        "e4x": false, // Pass E4X xml literals through untouched
        "jslint_happy": false, // if true, then jslint-stricter mode is enforced. Example function () vs function()
        "brace_style": "collapse", // "collapse" | "expand" | "end-expand". put braces on the same line as control statements (default), or put braces on own line (Allman / ANSI style), or just put end braces on own line.
        "keep_array_indentation": false, // keep array identation.
        "keep_function_indentation": false, // keep function identation.
        "eval_code": false, // eval code
        "unescape_strings": false, // Decode printable characters encoded in xNN notation
        "wrap_line_length": 0, // Wrap lines at next opportunity after N characters
        "break_chained_methods": false, // Break chained method calls across subsequent lines
        "end_with_newline": false, // Add new line at end of file
        "comma_first": false // Add comma first
    },
    "codeformatter_css_options": {
        "syntaxes": "css,less", // Syntax names which must process CSS formatter
        "format_on_save": false, // Format on save
        "indent_size": 4, // Indentation size
        "indent_char": " ", // Indentation character
        "indent_with_tabs": false, // Indent with one tab (overrides indent_size and indent_char options)
        "selector_separator_newline": false, // Add new lines after selector separators
        "end_with_newline": false, // Add new line of end in file
        "newline_between_rules": false, // Add new line between rules
        "eol": "\n" // EOL symbol
    },
    "codeformatter_scss_options": {
        "syntaxes": "scss", // Indentation size
        "format_on_save": false, // Format on save
        "indent_size": 2, // Indentation size
        "indent_char": " ", // Indentation character
        "indent_with_tabs": false, // Indent with one tab (overrides indent_size and indent_char options)
        "selector_separator_newline": true, // Add new lines after selector separators
        "end_with_newline": true // Add new line of end in file
    },
    "codeformatter_html_options": {
        "syntaxes": "html,asp,xml", // Syntax names which must process HTML formatter
        "format_on_save": false, // Format on save
        "indent_size": 4, // indentation size
        "indent_char": " ", // Indentation character
        "indent_with_tabs": false, // Indent with one tab (overrides indent_size and indent_char options)
        "preserve_newlines": false, // Preserve existing line-breaks
        "max_preserve_newlines": 10, // Maximum number of line-breaks to be preserved in one chunk
        "indent_tags": "html|head|body|div|nav|ul|ol|dl|li|table|thead|tbody|tr|th|td|blockquote|select|form|option|optgroup|fieldset|legend|label|header|section|aside|footer|figure|video|datalist|keygen|audio|embed|source|track|output|article|bdi|details|dialog|figcaption|main|mark|menuitem|meter|nav|progress|rp|rt|ruby|summary|time|wbr" // List of tags (defaults to indent) that should be reformatted. Example "div|p|li|table"
    },
    "codeformatter_python_options": {
        "syntaxes": "python", // Syntax names which must process Python formatter
        "format_on_save": false, // Format on save
        "indent_size": 1, // indentation size
        "indent_with_tabs": true, // Indent with tabs or spaces
        "max_char": 80, // Width of output lines in characters.
        "assignment": " = ", // This is how the assignment operator is to appear.
        "function_param_assignment": "=", // This is how function-parameter assignment should appear.
        "function_param_sep": ", ", // This is how function parameters are separated.
        "list_sep": ", ", // This is how list items are separated.
        "subscript_sep": "=", // This is how subscripts are separated.
        "dict_colon": ": ", // This separates dictionary keys from values.
        "slice_colon": ":", // this separates the start:end indices of slices.
        "comment_prefix": "# ", // This is the sentinel that marks the beginning of a commentary string.
        "shebang": "#!/usr/bin/env python", // Hashbang, a line-one comment naming the Python interpreter to Unix shells.
        "boilerplate": "", // Standard code block (if any). This is inserted after the module doc string on output.
        "blank_line": "", // This is how a blank line is to appear (up to the newline character).
        "keep_blank_lines": true, // If true, preserve one blank where blank(s) are encountered.
        "add_blank_lines_around_comments": true, // If true, set off comment blocks with blanks.
        "add_blank_line_after_doc_string": true, // If true, add blank line after doc strings.
        "max_seps_func_def": 3, // Split lines containing longer function definitions.
        "max_seps_func_ref": 5, // Split lines containing longer function calls.
        "max_seps_series": 5, // Split lines containing longer lists or tuples.
        "max_seps_dict": 3, // Split lines containing longer dictionary definitions.
        "max_lines_before_split_lit": 2, // Split string literals containing more newline characters.
        "left_margin": "", // This is how the left margin is to appear.
        "normalize_doc_strings": false, // If true, normalize white space in doc strings.
        "leftjust_doc_strings": false, // If true, left justify doc strings.
        "wrap_doc_strings": false, // If true, wrap doc strings to max_char.
        "leftjust_comments": false, // If true, left justify comments.
        "wrap_comments": false, // If true, wrap comments to max_char.
        "double_quoted_strings": false, // If true, use quotes instead of apostrophes for string literals.
        "single_quoted_strings": false, // If true, use apostrophes instead of quotes for string literals.
        "can_split_strings": false, // If true, longer strings are split at the max_char.
        "doc_tab_replacement": "....", // This literal replaces tab characters in doc strings and comments.
        // Optionally preserve unassigned constants so that code to be tidied
        // may contain blocks of commented-out lines that have been no-op'ed
        // with leading and trailing triple quotes.  Python scripts may declare
        // constants without assigning them to a variables, but CodeFormatter
        // considers this wasteful and normally elides them.
        "keep_unassigned_constants": false,
        // Optionally omit parentheses around tuples, which are superfluous
        // after all.  Normal CodeFormatter behavior will be still to include them
        // as a sort of tuple display analogous to list displays, dict
        // displays, and yet-to-come set displays.
        "parenthesize_tuple_display": true,
        // When CodeFormatter splits longer lines because max_seps
        // are exceeded, the statement normally is closed before the margin is
        // restored.  The closing bracket, brace, or parenthesis is placed at the
        // current indent level.  This looks ugly to "C" programmers.  When
        // java_style_list_dedent is True, the closing bracket, brace, or
        // parenthesis is brought back left to the indent level of the enclosing
        // statement.
        "java_style_list_dedent": false
    },
    "codeformatter_vbscript_options": {
        "syntaxes": "vbscript", // Syntax names which must process VBScript formatter
        "format_on_save": false, // Format on save
        "indent_size": 1, // indentation size
        "indent_char": "\t", // Indentation character
        "indent_with_tabs": true, // Indent with one tab (overrides indent_size and indent_char options)
        "preserve_newlines": true, // Preserve existing line-breaks
        "max_preserve_newlines": 10, // Maximum number of line-breaks to be preserved in one chunk
        "opening_tags": "^(Function .*|Sub .*|If .* Then|For .*|Do While .*|Select Case.*)", // List of keywords which open a new block
        "middle_tags": "^(Else|ElseIf .* Then|Case .*)$", // List of keywords which divide a block, but neither open or close the block
        "closing_tags": "(End Function|End Sub|End If|Next|Loop|End Select)$" // List of keywords which close an open block
    },
}

**Comment by EdwinPalacios** [comment]
I've found a solution and was put in the user configuration the syntaxis package.

```javascript
"codeformatter_php_options": {
      "syntaxes": "php",
      "php_path": "C:/xampp/php/php.exe"
}
```
for some reason does not take the default settings.

**Comment by swedkg** [comment]
Adding  "syntaxes": "php" worked for me too. Thanks a lot!

**Comment by 01271** [comment]
Ok well, upgrading from php 5.6 to php 7 worked... It shouldn't needed that step but thankfully I don't have a workplace where I require a specific php version.

**Comment by olegwn** [comment]
commenting out User settings worked for me (JavaScript)

**Comment by bostrom** [comment]
Adding the "syntaxes" configuration option to codeformatter user settings seems to work! No need to add all configuration options, only the ones you override, but syntaxes apparently needs to be included.

**Comment by aske-cph** [comment]
I have the same problem as @01271  on OSX El Capitan. 

I get the error :

PHP needs to be a minimum version of PHP 5.6.0

I have added the options 
```
"syntaxes": "php", // Syntax names which must process PHP formatter
"php_path": "/usr/local/php5/bin/php", // Path for PHP executable, e.g. "/usr/lib/php" 
```

"which php" on terminal gives me: 

> /usr/local/php5/bin/php


"php -v" in terminal gives me :  

> PHP 7.0.2 (cli) (built: Jan  8 2016 10:14:20) ( NTS )

**Comment by thecotne** [comment]
https://github.com/akalongman/sublimetext-codeformatter/issues/181#issuecomment-194391900

**Comment by toididau456** [comment]
+EdwinPalacios that right.
"codeformatter_php_options": {
      "syntaxes": "php",
      "php_path": "C:/xampp/php/php.exe"
}
this is problem!!
