### ISSUE TITLE
Can't format blade files

### ISSUE THREAD

**Issue by Nisthar** [akalongman/sublimetext-codeformatter#176]
I am using laravel. I can't format blade template files using codeformatter.

**Comment by thecotne** [comment]
i think you need to add blade in settings 
https://github.com/akalongman/sublimetext-codeformatter/blob/master/CodeFormatter.sublime-settings#L77

**Comment by thecotne** [comment]
https://github.com/akalongman/sublimetext-codeformatter/issues/43#issuecomment-194387767
