### ISSUE TITLE
PHP CodeFormatter is broken after latest updates

### ISSUE THREAD

**Issue by coscho** [akalongman/sublimetext-codeformatter#178]
CodeFormatter is broken after latest updates ... it require php 5.6 ... but formatted is not right ... 

EX : when I try to formate this code:

<?php 

defined('BASEPATH') OR exit('No direct script access allowed');

class Public extends Public_Controller {

	public function about_us()
	{
		$this->outputData['css'] = array(
            base_url() . 'assets/css/about.css'
        );		
		$this->load_view('public/about_us');
	
	}
}

IT BECOMES : 
<?php

defined('BASEPATH') or exit('No direct script access allowed');

class extendsPublic_Controller{public function about_us()
    {
        $this->outputData['css'] = array(
            base_url() . 'assets/css/about.css',
        );
        $this->load_view('public/about_us');

    }
}

TOTALLY WRONG ... what is going on??

**Comment by akalongman** [comment]
You've  update settings for CodeFormatter?

**Comment by coscho** [comment]
I forgot ... updating right now ...

**Comment by coscho** [comment]
Yes ... I added the path to php executable ... still broken ...

**Comment by coscho** [comment]
Here are php settings :
"codeformatter_php_options": {
        "syntaxes": "php", // Syntax names which must process PHP formatter
        "php_path": "/usr/bin/php", // Path for PHP executable, e.g. "/usr/lib/php" or "C:/Program Files/PHP/php.exe". If empty, uses command "php" from system environments
        "format_on_save": false, // Format on save
        "psr1": true, // Activate PSR1 style
        "psr1_naming": true, // Activate PSR1 style - Section 3 and 4.3 - Class and method names case
        "psr2": true, // Activate PSR2 style
        "indent_with_space": 4, // Use spaces instead of tabs for indentation
        "enable_auto_align": true, // Enable auto align of = and =>
        "visibility_order": true, // Fixes visibiliy order for method in classes - PSR-2 4.2
        "smart_linebreak_after_curly": true, // Convert multistatement blocks into multiline blocks
        // Enable specific transnformations. Example: ["ConvertOpenTagWithEcho", "PrettyPrintDocBlocks"]
        // You can list all available transnformations from command palette: CodeFormatter: Show PHP Transformations
        "passes": [],
        // Disable specific transnformations
        "exclude": [],
    },


I am using Ubuntu 14.04 ... path to php : /usr/bin/php

**Comment by akalongman** [comment]
Open console and copy here CodeFormatter error

**Comment by coscho** [comment]
I am not getting any error ...  I run the command ... it runs ... maybe I am doing something wrong ... but I don't see what ... I update php to 5.6 and set the path to settings file (user) ...  if it helps you debugging  I can give you my teamviewer ID ... everything was perfect until this morning updates.

**Comment by coscho** [comment]
works perfect ... is just when the class name is 'Public' .. is treated line 'public'  FROM public function(){} 
Thank you very much for your answers ...
