### ISSUE TITLE
So User with PHP < 5.6 cant use this plugin now?

### ISSUE THREAD

**Issue by n1colius** [akalongman/sublimetext-codeformatter#180]
After the update it turn out user must have PHP 5.6 or above to use this plugin..
i'm still using PHP 5.5 is that mean now i cannot use this plugin anymore? or is there another way to still make this plugin work?

Is it possible to undo the update and used an older version of this plugin so i can use it with PHP 5.5?
Thanks before

**Comment by akalongman** [comment]
Yes, you must have PHP 5.6 or above. Its phpfmt requirement, not my :) I suggest update your PHP to version 5.6 or if you can 7.0

**Comment by ccirello** [comment]
@n1colius you can replace the fmt.phar with an older version and use it with PHP 5.5. It is what in the original phpfmt plugin is called "PHP 5.5 compatibility mode". Try using this phar `https://github.com/phpfmt/sublime-phpfmt/blob/master/fmt.8.9.0.phar`

**Comment by akalongman** [comment]
@ccirello hey, thank you for your phpfmt :) I really interested, why phpfmt has restriction PHP 5.6 and above? 
@n1colius if you really want use PHP <5.6, I can add option in plugin for that. But I hightly recommend upgrade your PHP to 5.6 or better 7.0

**Comment by ccirello** [comment]
@n1colius @akalongman -- all you need to do is to upgrade your _local_ PHP. Not your server's.

@akalongman - regarding the restriction of PHP 5.6 is that is much harder to keep a performant code across versions - especially those that are old. As a matter of fact, after the upgrade from PHP 5.4 to 5.5 there was a slow down. And between PHP 5.5 and 5.6 there was another memory issue. So I am sticking only to those versions that are not close to EOL (http://php.net/supported-versions.php - you can see 5.5 is already orange).

The reason I kept the PHP 5.5 compatibility mode is that I could not convey to some non-english speaking users that all they need to do is upgrade their local PHP installations. Or even if you are using L/WAMP, you can always download the standalone php binary in some other place and use it separately.

**Comment by n1colius** [comment]
Thank you for the response..
All my environment / server are still using PHP 5.5, so i have to use PHP 5.5 on my local machine..
btw im using Ubuntu 14.04 on my local machine and the PHP from the repository are still on 5.5 version.. so i think there are many other user too that still using 5.5 version..

@akalongman 
if you can add that option, i really appreciate it. :)

@ccirello 
okey i will try that. :+1:

**Comment by n1colius** [comment]
@ccirello 
i already replace the fmt.phar with the https://github.com/phpfmt/sublime-phpfmt/blob/master/fmt.8.9.0.phar
but it still give me error...

Is there another step that i miss?

**Comment by akalongman** [comment]
No, I have not any check of PHP version in package

**Comment by ccirello** [comment]
Which error have you got?

**Comment by n1colius** [comment]
it give me this messages in popup

Format error:
Support for PHP 5.5.0 is deprecated. By June 20th, php.tools will no longer support it.
Formatting ...
! 0
! 0

 0 files untouched (cache hit)
 0 files total
Took 0s
Files not found: 
	 - /opt/sublime_text/--dry-run
	 - /opt/sublime_text/-

**Comment by ccirello** [comment]
That's a warning... Not the error itself. I guess the problem is on the additional params the are not backward compatible. So I guess you're in dead water...

**Comment by akalongman** [comment]
@ccirello in package I am using phpfmt.phar without php.tools.ini or any file config. Can be that issue?

**Comment by ccirello** [comment]
No the issue here is that it does not accept the dry run option that old release.

**Comment by akalongman** [comment]
@ccirello thank you, I really appreciate your feedback

@n1colius I can implement support for PHP 5.5 version in next release

**Comment by n1colius** [comment]
okay i just wait for the next release then.
Thank you very much for your help @ccirello @akalongman 
Good Day :+1:

**Comment by akalongman** [comment]
@ccirello exists fmt version for PHP  < 5.5?

**Comment by ccirello** [comment]
The one I linked here.

**Comment by akalongman** [comment]
That works on PHP 5.4? Or 5.3

**Comment by ccirello** [comment]
Ah! Sorry! :) I misunderstood you. No. the absolute minimum is PHP 5.5. But if you are looking for PHP 5.3 or 5.4, you might be interested on [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer#requirements).

**Comment by ccirello** [comment]
Check with them. But PHP-CS-Fixer works with PHP 5.3.6 or newer.

**Comment by akalongman** [comment]
Yes, but fmt is better :) Ok. thank you.

**Comment by n1colius** [comment]
hi @akalongman i see u added the option php55_compat mode there..
how can i used it? i try to add this line to my setting but it's still give me warning

"php55_compat": true, // PHP 5.5 compatible mode

**Comment by akalongman** [comment]
@n1colius Try version 3.1.3
