### ISSUE TITLE
Formatter for javascript not found

### ISSUE THREAD

**Issue by goranbrkic** [akalongman/sublimetext-codeformatter#181]
<img width="422" alt="screen shot 2016-01-21 at 11 47 34 am" src="https://cloud.githubusercontent.com/assets/4126614/12492395/d3bf0176-c034-11e5-9279-5b65c783e131.png">

**Comment by goranbrkic** [comment]
This is most likely a duplicate of https://github.com/akalongman/sublimetext-codeformatter/issues/173

**Comment by deeperton** [comment]
Have this issue too. Linux x64, Sublime 3083

**Comment by crapthings** [comment]
{
		"codeformatter_js_options": {
			"syntaxes": "javascript,json,JavaScript",
			"format_on_save": true
		}
	}

i think you should have
    
    "syntaxes": "JavaScript"

it works for me.

**Comment by goranbrkic** [comment]
:+1: 
Can confirm that **"syntaxes": "JavaScript"** fixes the issue.
Same thing with html formatter.

**Comment by thecotne** [comment]
this is issue with old settings file that does not have syntaxes specified
