### ISSUE TITLE
Error In Sublime Text 2

### ISSUE THREAD

**Issue by shirone** [akalongman/sublimetext-codeformatter#182]
![snap 2016-01-22 at 16 54 07](https://cloud.githubusercontent.com/assets/4187197/12507535/ef0b6f60-c128-11e5-9c24-ef0d9a0adc99.png)

Just Install but when i'm using, there is an error. How can i fix it?

**Comment by akalongman** [comment]
Will be fixed in next release. Probably today

**Comment by shirone** [comment]
i fixed it. luckily i just remove "," in line 159 in file CodeFormatter.sublime-settings
![snap 2016-01-22 at 17 02 14](https://cloud.githubusercontent.com/assets/4187197/12507720/150e74cc-c12a-11e5-911e-c20591e74c78.png)

to 

![snap 2016-01-22 at 17 02 29](https://cloud.githubusercontent.com/assets/4187197/12507724/1e0a40ec-c12a-11e5-932e-604ee2354b37.png)

**Comment by rosco9awj** [comment]
Please close this issue.
