### ISSUE TITLE
php not work with <? in begin

### ISSUE THREAD

**Issue by ildarkhasanshin** [akalongman/sublimetext-codeformatter#185]
<? in begin - not work
<?php - work

in phpfmt works with <? and <?php
https://packagecontrol.io/packages/phpfmt

**Comment by ildarkhasanshin** [comment]
in phpfmt works with <? and <?php

**Comment by akalongman** [comment]
I'm using fmt. Maybe settings is different?

**Comment by ildarkhasanshin** [comment]
default settings in phpfmt and codeformatter
can send both settings in profile's email?

**Comment by akalongman** [comment]
Sure, send to me

**Comment by ccirello** [comment]
The reason it is not working is because you have not enabled short tags on you php environment. Enable it, and it will work.

**Comment by ildarkhasanshin** [comment]
no
short_open_tag
local value on
master value on

**Comment by ildarkhasanshin** [comment]
up

**Comment by akalongman** [comment]
Can you send to me full CodeFormatter config. And also tell me your OS, PHP version, Sublime Text version

**Comment by ildarkhasanshin** [comment]
sent

**Comment by ildarkhasanshin** [comment]
up

**Comment by akalongman** [comment]
Fixed in version 3.1.3
