### ISSUE TITLE
Missing commas in CodeFormatter.sublime-settings

### ISSUE THREAD

**Issue by Pixelworlds** [akalongman/sublimetext-codeformatter#199]
Error trying to parse settings: Unexpected character, expected a comma or closing bracket in Packages/CodeFormatter/CodeFormatter.sublime-settings:88:9

Error trying to parse settings: Unexpected character, expected a comma or closing bracket in Packages/CodeFormatter/CodeFormatter.sublime-settings:179:9

**Comment by thecotne** [comment]
this was fixed  #198
