### ISSUE TITLE
Sudden Faulty Indentation in HTML

### ISSUE THREAD

**Issue by ashhem** [akalongman/sublimetext-codeformatter#201]
Hello,
I am writing a webpage using sublime text and have been using your CodeFormatter for a few months now. While it works great mostly, I am facing this weird issue where suddenly indentation fails in my file. Some part of file in indented, rest isn't. I am attaching a screen shot to show the same. I have blackened the code for confidential reasons. 
![codeformatterproblem](https://cloud.githubusercontent.com/assets/10893509/13629365/aec6596a-e5fe-11e5-8f05-9c20b67d6b87.png)
Can you please look into it?

**Comment by RevanProdigalKnight** [comment]
Why do you have `<img ...></img>`? The `<img>` tag is a singleton in HTML, it isn't supposed to have a closing tag.

**Comment by ashhem** [comment]
Perfect. That solved the issue. In the flow of closing tags, I accidentally closed that one too, and since I copy pasted the same lines, the mistake got repeated. That's for the apt solution!

**Comment by RevanProdigalKnight** [comment]
Glad that fixed the issue. I'm still going to try and incorporate a fix that will automatically get rid of closing tags on singletons for the future so that other people don't have this issue.
