### ISSUE TITLE
Problem formatting PHP file

### ISSUE THREAD

**Issue by ShavidzeT** [akalongman/sublimetext-codeformatter#204]
I have install codeformatter package on sublime text 3, I'm Ubuntu user and using ctrl+shift+p  I tried to search format as PHP syntax, but the result is same, it doesn't work for me.
I want to solve this problem.

**Comment by ildarkhasanshin** [comment]
1 use <?php instead <?
2 use https://github.com/phpfmt/sublime-phpfmt

**Comment by ShavidzeT** [comment]
@ildarkhasanshin I'm already using <?php but the problem is same.
But thanks for share me another package: phpfmt, it works great!
But I hope this problem will be solved on this package.

**Comment by ildarkhasanshin** [comment]
https://github.com/akalongman/sublimetext-codeformatter/issues/185

**Comment by akalongman** [comment]
I will check this problem soon

**Comment by ildarkhasanshin** [comment]
config in ubuntu

"codeformatter_php_options":
{
"syntaxes": "php",
"php_path": "/usr/bin/php",
"format_on_save": false,
"php55_compat": false,
"psr1": true,
"psr1_naming": false,
"psr2": true,
"indent_with_space": 2,
"enable_auto_align": true,
"visibility_order": true,
"smart_linebreak_after_curly": true,
"passes": [],
"exclude":["PSR1OpenTags"]
}

**Comment by akalongman** [comment]
@ShavidzeT @ildarkhasanshin  Fixed in version 3.1.3

@ShavidzeT მიხარია ქართველების დანახვა გითჰაბზე :)

**Comment by ShavidzeT** [comment]
@akalongman როცა დავგუგლე sublime text php formatter, პირველივე შედეგი შენი რეპო იყო და მე ეგ გამიხარდა ;)
