### ISSUE TITLE
Formatter for this file type (php) not found

### ISSUE THREAD

**Issue by numediaweb** [akalongman/sublimetext-codeformatter#206]
I have installed the required software;

```
» php -v

PHP 5.6.19 (cli) (built: Mar  3 2016 12:09:49)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

But when I run the command formatter `CTRL + B` I get the error above.

**Comment by akalongman** [comment]
Shoe me your CF settings

**Comment by REJack** [comment]
you need to set `php_path` in your codeformatter config to the php binary

**Comment by JMichaelRoach** [comment]
I get the same error (using version 3.x.x), regardless how I set the `php_path`.  In fact, I seem to get the error regardless of syntax (html, php, javascript, etc.).

**Comment by REJack** [comment]
are you get a specific error message?

**Comment by JMichaelRoach** [comment]
CodeFormatter

Formatter for this file type (php) not found.

**Comment by REJack** [comment]
post me your both configs (user and default)

**Comment by REJack** [comment]
it seems you have `syntaxes` empty in `codeformatter_php_options`

**Comment by JMichaelRoach** [comment]
I also get the same for other syntaxes.  Formatter for this file type (javascript) not found.

Here's the default (section):

`    "codeformatter_php_options":`
`    {`
`        "syntaxes": "php",`
`        "php_path": "",`
`        "format_on_save": false,`
`        "php55_compat": false,`
`        "psr1": false,`
`        "psr1_naming": false,`
`        "psr2": true,`
`        "indent_with_space": 4,`
`        "enable_auto_align": true,`
`        "visibility_order": true,`
`        "smart_linebreak_after_curly": true,`
`        "passes": [],`
`        "exclude": []`
`    },`

Here's the user (section):

`   "codeformatter_php_path": "C:/Program Files (x86)/PHP/php.exe",`
``
`   "codeformatter_php_options":`
`   {`
`      "php_path": "",`
`      "indent_size": 3,`
`      "indent_with_tabs": false,`
`      "indent_style": "k&r",`
`      "pear": true,`
`      "pear_add_header": "",`
`      "pear_newline_class": true,`
`      "pear_newline_trait": true,`
`      "pear_newline_function": false,`
`      "pear_switch_without_indent": false,`
`      "equals_align": false,`
`      "preserve_newlines": false,`
`      "newline_before_comment": true,`
`      "new_line_before": "function,switch,while,for,try",`
`      "format_array_nested": true,`
`      "php55_compat": false`
`   },`

**Comment by REJack** [comment]
you use options they are not available, i would try to reset user config, and the php path from `codeformatter_php_path` should be in `codeformatter_php_options` => `php_path`,

`codeformatter_php_path` is also not a available option.


```

**Comment by REJack** [comment]
you need on your user config the `syntaxes` too, basically it should be the same structure.

if i remove `syntaxes` from my user config i get the same error like you

**Comment by armandoclasslife** [comment]
it happens if you create a user config file. I created it to test, emptied it later and started failing. After that, I deleted the file from:
/home/XXXXXX/.config/sublime-text-3/Packages/User

And working again.
