### ISSUE TITLE
[Errno 32] Broken pipe

### ISSUE THREAD

**Issue by hsnk** [akalongman/sublimetext-codeformatter#21]
I'm running ST 2.0.2 on Win7 64bit. I installed Codeformatter without the dependencies (node and Python) and got this error. So I installed them, restarted the editor and tried and get the same error.
Interesting to note is that the "Codeformatter: format" command does not appear in the command palette. 
What could I be missing?

**Comment by darkpole** [comment]
yes, i have same error Format error :
[Errno 32] Broken pipe
on sublime text 2

**Comment by scottfriebel** [comment]
I am also still getting this error in the latest version after the switch to phpfmt in Sublime 3.

**Comment by akalongman** [comment]
Try chmod +x executable phpfmt.phar file
