### ISSUE TITLE
Void tags not closing properly

### ISSUE THREAD

**Issue by fernandobandeira** [akalongman/sublimetext-codeformatter#210]
I've noticed that the formatter is forcing the images to the XHTML syntax, for example:

```html
<img alt="test" src="test" title="test">
    <span>
        test
    </span>
```
`ctrl + alt + f`

```html
<img alt="test" src="test" title="test">
    <span>
        test
    </span>
</img>
```

If there's a need to support XHTML should'nt it format like this?
```html
<img alt="test" src="test" title="test"/>
<span>
    test
</span>
```

AFAIK:

html5
`<img src="test">`
html5 supports, xhtml
`<img src="test"/>`
xhtml only
`<img src="test"></img>`

This only happens if the img is in this format: `<img src="test">` and there's any text/html(anything) after it, if the image is like `<img src="test"/>` it doesn't change

**Comment by fhb12345** [comment]
It's not only with images, this happens with any element that doesn't have a closing tag, for example:

```html
a
<br>
b
```
`ctrl + alt + f`
```html
a
<br>
    b
</br>
```

**Comment by akalongman** [comment]
Show me full html file example please
