### ISSUE TITLE
CodeFormatter  Format error: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by vnt** [akalongman/sublimetext-codeformatter#212]
Hi,
I have a problem with code formatter (sublime 3 on mac os x 10.11.4):

Format error:
[Errno 13] Permission denied

how can I fix it?

**Comment by akalongman** [comment]
When CF shows this error?

**Comment by vnt** [comment]
Into a page .php
Tools-> Command Palette -> CodeFormatter format code

**Comment by akalongman** [comment]
Try run 

    sudo chmod +x /[Sublime Packages Path]/CodeFormatter/codeformatter/lib/phpbeautifier/fmt.phar

and let me know result

**Comment by vnt** [comment]
I run the command,
-rwxr-xr-x@ 1 vcx  staff  353260 31 Mar 07:41 fmt.8.9.0.phar
-rwxr-xr-x@ 1 vcx  staff  349804 31 Mar 07:41 fmt.phar
But I have always the same error

**Comment by epregboy** [comment]
I meet the same question in mac os x on 10.11.4,after run chmod +x in to fmt.phar. The question also exists? Are u has fixed it? 3Q!

**Comment by hjmf1954** [comment]
Exactly the same error. All suggestions have been performed without any result however. Any suggestions?

**Comment by REJack** [comment]
i dont know but your config could help, 
i think you missed to config the `php_path`

i got a similar error on windows before i changed my `php_path` to my php.exe, 
it doesn't use php available over the environment `PATH`

**Comment by himanshutecstub** [comment]
I added 'php_path' (PHP7 - ubuntu) in configuration and also set 777 permission of 'CodeFormatter' but till got error.
