### ISSUE TITLE
Format HTML get error

### ISSUE THREAD

**Issue by n1colius** [akalongman/sublimetext-codeformatter#218]
when i want to format html file.. i got this error
'list_iterator' object has no attribute 'next'

**Comment by RevanProdigalKnight** [comment]
Could you provide a sample that exhibits this behavior? Also, what are your CodeFormatter settings?

**Comment by daesolus** [comment]
I have the same issue. each time that i try to format html file, I got this error. I'm using default settings.

**Comment by momoca** [comment]
I have the same issue.
|||||||||||||||||||||||||
VVVVVVVVVVV
```
Unable to load BeautifulSoup HTML formatter. The old RegExp-based formatter was automatically used for you instead.
error: CodeFormatter
```

**Comment by RevanProdigalKnight** [comment]
@momoca It sounds like you have a different issue from the others. Try setting `"formatter_version": "regexp"` in your CodeFormatter settings.

**Comment by momoca** [comment]
@RevanProdigalKnight Resolve a mistake, but there is still the following error.
```
Format error:
'list_iterator' object has no attribute 'next'
error: CodeFormatter
```

**Comment by RevanProdigalKnight** [comment]
@momoca Okay, can you post an example that causes this behavior?

**Comment by momoca** [comment]
@RevanProdigalKnight 
```html
<meta charset="utf-8"/>
<meta name="author" content="Momoca"/>
<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'/><![endif]-->
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
<title>{:L('title')}</title>
<meta name="keywords" content="{:C('SITE_KEYWORDS')}"/>
<meta name="description" content="{:C('SITE_DESCRIPTION')}"/>
```

**Comment by RevanProdigalKnight** [comment]
Hmmm, strange. I'm not getting that error when formatting. What are the rest of your settings?

**Comment by momoca** [comment]
@RevanProdigalKnight Well ... I re-installed. The problem still exists.
sublimetext dev 3111,
win10 x64...
...You also need to know what information?

**Comment by RevanProdigalKnight** [comment]
@momoca No, it's because I didn't future-proof my code. I'm using `it = iter(list) ... it.next()`, which as it turns out is invalid in Python 3. I should have used `next(it)` instead, according to what I'm reading.

**Comment by momoca** [comment]
@RevanProdigalKnight #fixed

**Comment by n1colius** [comment]
i am using the default setting too, this is the sample of html file i try to format..


	
    <select name="{NAME}" id="{ELMID}" style="{STYLE}" {SCRIPT}>
	
		<option value="{ID}" {SELECTED}>{NAME}</option>
	       
	</select>
    
    <button type="button" id="button_add_{ELMID}" value="new" ><img src="assets/images/buttons/button-add.gif" /></button>
    <script type="text/javascript">
    var popup{ELMID};
    
    $(document).ready(function(){    
        $('#div_{ELMID}').off('click', '#button_add_{ELMID}').on('click', '#button_add_{ELMID}', function(){
            popup{ELMID} = showGtPopup('{URL}', ' ', null, null, 'popup-{ELMID}');
            return false;
        })
    });
    </script>        
    
	


i am using Ubuntu 14.04 Sublime Text 3 3103

**Comment by momoca** [comment]
@n1colius #219 https://github.com/akalongman/sublimetext-codeformatter/pull/219/commits/438f9909fd61e05fd371c6f19273e358bd6ea962

**Comment by n1colius** [comment]
i already update the code.. now the error not showing anymore but it looks like my html file not getting formatted.. it looks the same and got no changes at all after i apply the format.

this is my setting

"codeformatter_html_options":
{
      "syntaxes": "html,asp,xml",
      "format_on_save": false,
      "indent_size": 3,
      "indent_char": " ",
      "indent_with_tabs": false,
      "exception_on_tag_mismatch": false,
      "expand_javascript": false, 
      "expand_tags": false,
      "minimum_attribute_count": 2,
      "first_attribute_on_new_line": false,
      "reduce_empty_tags": false,
      "custom_singletons": ""   
}

this is the html file i try to format

    <form id="form_search" class="xhr dest_subcontent-element dataquest" method="post" action="{URL}">
    <input type="hidden" id="mode" name="mode" value="{MODE}" />
    <table class="table-search">
      <tbody>
          <tr>
              <th style="width:20%;"></th>
              <td><input type="text" name="name" value="{NAME}" size="40" />&nbsp;<button class="btn"></button></td>
          </tr>
      </tbody>
    </table>
    </form>

**Comment by RevanProdigalKnight** [comment]
@n1colius With your settings, you're currently configured to use the BeautifulSoup HTML formatter that @akalongman introduced. Try adding `"formatter_version": "regexp"` to your settings.

**Comment by momoca** [comment]
html config eg:
**"formatter_version": "regexp", // Which formatter to use. Current options are "bs4" and "regexp". If an error occurs while loading the bs4 formatter, the regexp formatter will automatically** 
```
    "codeformatter_html_options": {
        "syntaxes": "html,blade,asp,xml", // Syntax names which must process HTML formatter
        "format_on_save": false, // Format on save
        "formatter_version": "regexp", // Which formatter to use. Current options are "bs4" and "regexp". If an error occurs while loading the bs4 formatter, the regexp formatter will automatically be used
        "indent_size": 4, // indentation size
        "indent_char": " ", // Indentation character
        "indent_with_tabs": false, // Indent with one tab (overrides indent_size and indent_char options)
        "exception_on_tag_mismatch": false, // If the last closing tag is not at the same indentation level as the first opening tag, there's probably a tag mismatch in the file
        "expand_javascript": false, // (Under construction) Expand JavaScript inside of <script> tags (also affects CSS purely by coincidence)
        "expand_tags": false, // Expand tag attributes onto new lines
        "minimum_attribute_count": 2, // Minimum number of attributes needed before tag attributes are expanded to new lines
        "first_attribute_on_new_line": false, // Put all attributes on separate lines from the tag (only uses 1 indentation unit as opposed to lining all attributes up with the first)
        "reduce_empty_tags": false, // Put closing tags on same line as opening tag if there is no content between them
        "custom_singletons": "" // Custom singleton tags for various template languages outside of the HTML5 spec
    },
```
change file `codeformatter/lib/htmlbeautifier/__init__.py` eg:https://github.com/akalongman/sublimetext-codeformatter/pull/219/commits/438f9909fd61e05fd371c6f19273e358bd6ea962

**Comment by RevanProdigalKnight** [comment]
@n1colius I'm not sure what's going on, because the snippet you provided is formatting fine for me now in both ST2 and ST3 with the settings you provided (sans a small error with the template comments causing the next line not to unindent, but formatting again fixes this). Is there anything in the console when you attempt to format the file?

**Comment by edushare** [comment]
same error here

**Comment by n1colius** [comment]
@RevanProdigalKnight 
well this is weird then.. console not showing anything..
i guess it will be remain mystery :(

**Comment by edushare** [comment]
![image](https://cloud.githubusercontent.com/assets/9190552/14717917/3c4b63b8-0826-11e6-891a-8042827fb6d2.png)

**Comment by RevanProdigalKnight** [comment]
@n1colius I'll continue to look in to the issue. It's weird that it won't format for you.

@edushare #219 will address your issue once merged. If you need an immediate fix and don't mind going into the package files yourself, you can apply the fix manually by changing the [appropriate line](https://github.com/akalongman/sublimetext-codeformatter/pull/219/commits/438f9909fd61e05fd371c6f19273e358bd6ea962)

**Comment by n1colius** [comment]
@RevanProdigalKnight thank you very much :)

**Comment by maxmadknight** [comment]
Have same issue +1

**Comment by newjunkcity** [comment]
I am also getting the error message : 
> Unable to load BeautifulSoup HTML formatter. The old RegExp-based formatter was automatically used for you instead.

Rather than "solving" this by specifying the RegExp formatter by default, is anyone able to shed any light onto why the bs4 formatter isn't loading ?
Is it automatically downloaded and installed by PackageControl, or must one add another package ?

Many thanks.

**Comment by motir** [comment]
+1 same error here
Please LMK if I can help with anything (logs? snippets?)

**Comment by Metalchocobo** [comment]
+1
Same here

**Comment by tbogard** [comment]
+1 Same error here.

**Comment by canercak** [comment]
+1 same for me

**Comment by RevanProdigalKnight** [comment]
@newjunkcity:

> Rather than "solving" this by specifying the RegExp formatter by default, is anyone able to shed any light onto why the bs4 formatter isn't loading ?
Is it automatically downloaded and installed by PackageControl, or must one add another package ?

BeautifulSoup 4 is being included in the CodeFormatter plugin, but (for me, at least) there's a soft compilation error when Sublime Text loads the plugins. Before I added a `try/except` clause around the import for BeautifulSoup, it was throwing an exception that caused the entire plugin to not finish loading. I've added some logging to my local version, and this is the output:

```
Traceback (most recent call last):
  File ".\codeformatter\htmlformatter.py", line 23, in <module>
    from bs4 import BeautifulSoup
  File "<...>\codeformatter\lib\htmlbeautifier\bs4\__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "<...>\codeformatter\lib\htmlbeautifier\bs4\builder\__init__.py", line 4, in <module>
    from bs4.element import (
  File "<...>\codeformatter\lib\htmlbeautifier\bs4\element.py", line 8, in <module>
    from bs4.dammit import EntitySubstitution
  File "<...>\codeformatter\lib\htmlbeautifier\bs4\dammit.py", line 13, in <module>
    from html.entities import codepoint2name
ImportError: No module named html.entities
```

**Comment by jstillwa** [comment]
Note the return lambda match: self.reindent(next(it),match) error is in the coldfusion beautifier as well. 

Cheers!
-J

**Comment by MapleLeap** [comment]
+1error. Here

**Comment by Deus-Vult** [comment]
If you look in the file
`sublime-text-3/Packages/CodeFormatter/codeformatter/htmlformatter.py`
the following lines can be found:
```
import htmlbeautifier
use_bs4 = True
try:
    from bs4 import BeautifulSoup
    use_bs4 = False
except:
    use_bs4 = False
```

I'm not sure if this was to intentionally disable Beautiful Soup or if it's just a bug that crept in. Personally I altered it to the following snippet with complete disregard to the reason behind it and will be watching for side effects.

```
import htmlbeautifier
use_bs4 = True
try:
    from bs4 import BeautifulSoup
    use_bs4 = True
except:
    use_bs4 = False
```

**Comment by RevanProdigalKnight** [comment]
@Deus-Vult That was a debugging line that I forgot to remove before committing, and is also fixed in #219. There shouldn't be any side effects from either removing the line or changing it as you did.

**Comment by qkdreyer** [comment]
OSX Users that want an easy fix while PR gets acceptd : 

cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/CodeFormatter && curl https://patch-diff.githubusercontent.com/raw/akalongman/sublimetext-codeformatter/pull/219.patch | git apply

**Comment by canercak** [comment]
that fixed it thank you

**Comment by MapleLeap** [comment]
Thank upstairs,The prioblem has been resolved;
