### ISSUE TITLE
Format error: 'list_iterator' object has no attribute 'next'

### ISSUE THREAD

**Issue by diogopms** [akalongman/sublimetext-codeformatter#220]
I am using Sublime Text version 3 with the package CodeFormatter.

All the formaters works great, except the HTML part.

WHen i tried to use that, i am receiving this error:

`Format error:
'list_iterator' object has no attribute 'next'`

**Comment by RevanProdigalKnight** [comment]
This will be addressed by #219.

**Comment by hexiyou** [comment]
@RevanProdigalKnight  Nice,it worked!

**Comment by bramburn** [comment]
thanks buddy!

**Comment by tbogard** [comment]
Still present, I patched the file as indicated in #219 and it didn't work.

**Comment by RevanProdigalKnight** [comment]
@tbogard I know this is probably a stupid question, but did you restart Sublime Text after patching?

**Comment by tbogard** [comment]
@RevanProdigalKnight yes, I did... and it worked out???? Thanks :dancer:
