### ISSUE TITLE
indent 2 buggy in php

### ISSUE THREAD

**Issue by abumalick** [akalongman/sublimetext-codeformatter#230]
Hello, I wanted to set php indent to 2
under
"codeformatter_php_options":
I changed : 
"indent_with_space": 2, // Use spaces instead of tabs for indentation

It works when I format the file, but when I press "tab" in php files it makes 4 spaces.
And I am 100% sure it is from codeformatter : when I desactive it tab makes 2 spaces.

Do you have a fix for that ?

**Comment by REJack** [comment]
i think you use in SublimeText `"translate_tabs_to_spaces": true`, if yes try to change `tab_size` to 2.

**Comment by abumalick** [comment]
Yes, it don't fix the bug.

On Fri, Jun 3, 2016 at 9:44 PM, Raphael Jackstadt <notifications@github.com>
wrote:

> i think you use in SublimeText "translate_tabs_to_spaces": true, if yes
> try to change tab_size to 2.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/akalongman/sublimetext-codeformatter/issues/230#issuecomment-223675866>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AH_TYbh-RTqB4I96Vy8bi3vqOg5AKKQiks5qIIQ2gaJpZM4IkFJg>
> .
>



-- 
Abdullah Hilson
+32 (0) 485 554 661
abdullah.hilson@gmail.com

**Comment by REJack** [comment]
i don't have this bug, if i change `tab_size` in `Settings - User` to 2, 
it creates 2 spaces except I'm in a function with input then it goes to the line from the input 

I'm using Sublime Text 3 Build 3114

**Comment by abumalick** [comment]
I disabled the plugin for some days and now enabled it and I cannot reproduce the bug anymore.
Thanks for your help !
