### ISSUE TITLE
fmt.phar multiple versions

### ISSUE THREAD

**Issue by ccirello** [akalongman/sublimetext-codeformatter#233]
```
➜  phpbeautifier git:(master) php fmt-php7.phar  --version
fmt-php7.phar 20.5.0
➜  phpbeautifier git:(master) php fmt-php55.phar  --version
fmt-php55.phar 8.9.0
➜  phpbeautifier git:(master) php fmt.phar --version
fmt.phar 19.6.4
```

However https://github.com/akalongman/sublimetext-codeformatter/blob/master/codeformatter/phpformatter.py#L77-L80 only uses 19.6.4 and 8.9.0. I suggest upgrading the php7 support to phpfmt fmt.phar 803.5 (https://github.com/phpfmt/releases/tree/master/releases/lts)

**Comment by ccirello** [comment]
You can track the releases from https://raw.githubusercontent.com/phpfmt/releases/master/releases.json and add some support for automatic updates.

Like https://github.com/phpfmt/sublime-phpfmt/blob/master/phpfmt.py#L937-L953

**Comment by akalongman** [comment]
I plan setting php version from config or detect automatically. I think many users have PHP 5.5 or 5.6

**Comment by ccirello** [comment]
> I think many users have PHP 5.5 or 5.6

You understand that fmt.phar for these versions are not getting any kind of updates, right?

**Comment by akalongman** [comment]
Yes. If they will open issues related PHP 5.X, I will suggest upgrade to PHP 7 :)
