### ISSUE TITLE
php option indent_with_space is not working

### ISSUE THREAD

**Issue by bgarrison25** [akalongman/sublimetext-codeformatter#234]
So, our company prefers tabs for indenting and spaces for alignment. Im not here to start a holy war. I simply need to be able to have this plugin stop changing all my tab indents into spaces. 

I go into my settings and make the following changes:

```
"codeformatter_php_options":
    {
       "php55_compat": true, // PHP 5.5 compatible mode
       "indent_with_space": false, // Use spaces instead of tabs for indentation
    },
```

However, every time i format my code using your plugin it STILL overrides my tabs. Any ideas?

**Comment by bgarrison25** [comment]
nevermind.....if your using psr2 then you also have to put "PSR2IndentWithSpace" in the exclude array This is a non issue but might be worth mentioning in the docs :)

**Comment by bgarrison25** [comment]
I apologize. I tricked myself by turning off the "on_save" feature. It is still converting all of my tabs to spaces even if i exclude that specific transformation. No idea why

**Comment by REJack** [comment]
try to set `psr2` to `false`.


i have not this problem with my config 
```
        "format_on_save": true, // Format on save
        "psr1": false, // Activate PSR1 style
        "psr1_naming": false, // Activate PSR1 style - Section 3 and 4.3 - Class and method names case
        "psr2": false, // Activate PSR2 style
        "indent_with_space": false, // Use spaces instead of tabs for indentation
        "enable_auto_align": false, // Enable auto align of = and =>
        "visibility_order": false, // Fixes visibility order for method in classes - PSR-2 4.2
        "smart_linebreak_after_curly": true, // Convert multistatement blocks into multiline blocks
```

**Comment by bgarrison25** [comment]
Problem is I WANT all the other PSR2 formatting. So I went into the code
and found out which transformation passes it was doing and included all of
them but the space indentation one.

**Comment by REJack** [comment]
oh ok i understand :smile: 

i would say its more a issue with [phpfmt](https://github.com/phpfmt/fmt) and not with codeformatter

**Comment by danielfranz** [comment]
I have the same issue. I can't seem to get it to indent PHP with tabs.

**Comment by akalongman** [comment]
Config signature will be changed, please look at https://github.com/akalongman/sublimetext-codeformatter/issues/355#issuecomment-381722577
