### ISSUE TITLE
minimum version of PHP 5.6.0 error even if i have PHP 5.6.15

### ISSUE THREAD

**Issue by avinashjoshi** [akalongman/sublimetext-codeformatter#239]
I am unable to figure out why this is not working. I have PHP 5.6.15:

``` shell
$ php --version
PHP 5.6.15 (cli) (built: Oct 31 2015 07:39:39) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Retinas
$ which php
/usr/local/opt/php56/bin/php
```

Also, executing the `fmt.php` on command runs successfully!

``` shell
$ /usr/bin/env php ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/CodeFormatter/codeformatter/lib/phpbeautifier/fmt.phar --cakephp -o=- ~/Desktop/test.php 
<?php
if ($a) {

} elseif ($b) {

}
?>
$ /usr/bin/env php ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/CodeFormatter/codeformatter/lib/phpbeautifier/fmt.phar --version
/Users/avi/Library/Application Support/Sublime Text 3/Packages/CodeFormatter/codeformatter/lib/phpbeautifier/fmt.phar 19.6.4
```

I did set:

``` json
{ "php_path": "/usr/local/opt/php56/bin/php" }
```

Here is the error in SublimeText 3:
![screen shot](https://cloud.githubusercontent.com/assets/172230/15976663/a88aa6c8-2f19-11e6-8ccd-11c42ae43cce.png)

**Comment by REJack** [comment]
This is not really a error from CodeFormatter, its a error from phpfmt, 
but they stopped PHP5 support, CodeFormatter has for 5.5/5.6 old phpfmt versions. 

Do you have PHP5.5 or less on your Mac too? Your whole CodeFormatter config could help too :smile:.

**Comment by avinashjoshi** [comment]
I only have PHP 5.6 on my Mac (no other versions) 😬

Here is the CodeFormatter config:
```json
"codeformatter_php_options": {
    "enable_auto_align": true,
    "exclude": [],
    "format_on_save": false,
    "indent_with_space": 4,
    "passes": [],
    "php_path": "/usr/local/opt/php56/bin/php",
    "psr1": false,
    "psr1_naming": false,
    "psr2": true,
    "smart_linebreak_after_curly": true,
    "syntaxes": "php",
    "visibility_order": true
},
```

**Comment by REJack** [comment]
That's really curious, i noticed its able to insert in `php_path` only php without full path, then it use the installed version that's callable from any terminal window.

I don't know but you could test this, i tested CodeFormatter on my PC win 5.6.8 and it worked.
I personally use the latest versions of PHP actually 5.6.22 & 7.0.7.

**Comment by mancojiang** [comment]
same problem!

**Comment by taxaduq** [comment]
Is anyone trying to fix this? please?

**Comment by akalongman** [comment]
This issue is actual?

**Comment by ckegelman** [comment]
@akalongman it is still for me

**Comment by aa21** [comment]
@akalongman Hey man, 

I'm having the same issue also. 
<img width="431" alt="screen shot 2017-04-28 at 12 33 32 pm" src="https://cloud.githubusercontent.com/assets/486730/25514328/c7bc1926-2c0e-11e7-9748-c7bfda5a5152.png">

This is my php -v ouput:
<img width="471" alt="screen shot 2017-04-28 at 12 33 54 pm" src="https://cloud.githubusercontent.com/assets/486730/25514338/d7bf89d4-2c0e-11e7-8238-c22570eb5e05.png">

So yes. This issue is actual and still happening after one whole year. I just need to format the damn code, I don't want to install PHP 7 to format PHP 5.6. 

Thank you!

**Comment by akalongman** [comment]
Should be fixed by https://github.com/akalongman/sublimetext-codeformatter/issues/355#issuecomment-381722577
