### ISSUE TITLE
Keyword "use" remove by the phpfmt

### ISSUE THREAD

**Issue by macOneOone** [akalongman/sublimetext-codeformatter#242]
I'm using Laravel and phpfmt is removing the keyword "use" after the namespace declaration like:

```
namespace App\Http\Controllers;
use App\Customer as Customer;

```

and it's cleaning it for:
`
namespace App\Http\Controllers;
`

**Comment by hao203** [comment]
Yes, I also have the same error

**Comment by macOneOone** [comment]
I'm thinks it's not issue, but it prevents you from load unnecessary files or module. I did the same without any framework and i had the same result

**Comment by zezeron** [comment]
+1

I'm waiting for your answers

**Comment by thecotne** [comment]
this is expected behavior if you are not using `Customer` it will remove unused `use` statement 

![60835984](https://cloud.githubusercontent.com/assets/1606993/21583029/0c23ad88-d087-11e6-9333-7abb2c52d543.jpg)


closing as it's not a bug

**Comment by Raggok** [comment]
BUt what if im using it on a function

**Comment by ddon** [comment]
so far found one solution that if you add a comment at the end of the use statement and phpfmt leaves it as it:

use xxxxxx; // phpfmt:disable-line
