### ISSUE TITLE
Format Error if using AlignPHPCode

### ISSUE THREAD

**Issue by saurabh-gohil** [akalongman/sublimetext-codeformatter#250]
I get following error if I use AlignPHPCode in passes.
Format error:
PHP Notice:  Undefined offset: -1 in phar:///home/saurabhg/.config/sublime-text-3/Packages/CodeFormatter/codeformatter/lib/phpbeautifier/fmt.phar/fmt.stub.php on line 1973
Notice: Undefined offset: -1 in phar:///home/saurabhg/.config/sublime-text-3/Packages/CodeFormatter/codeformatter/lib/phpbeautifier/fmt.phar/fmt.stub.php on line 1973

How can I solve this error?
Your help is much appreciated.

**Comment by scottfriebel** [comment]
I get this same error. It appears to only happen if you have content after the first php closing tag "?>", whether that content be another block of php or html.

**Comment by runofthemill** [comment]
Same error running ST Dev 3120 with PHP 7.0.9

**Comment by akalongman** [comment]
Is this issue actual?

**Comment by thecotne** [comment]
same as #261

**Comment by subins2000** [comment]
This has been fixed in my fork of **phpfmt** : https://github.com/subins2000/phpfmt/commit/a71404acf4d20747792fabc603f93a6624612ae5

**Comment by akalongman** [comment]
subins2000 can you send me pull request with new phpfmt?

**Comment by akalongman** [comment]
https://github.com/akalongman/sublimetext-codeformatter/issues/355#issuecomment-381722577
