### ISSUE TITLE
在sublime text3中如何格式化es6的import代码风格

### ISSUE THREAD

**Issue by liyangmsn** [akalongman/sublimetext-codeformatter#256]
怎么能让import {}里的内容不换行
比如 
import React, {
Component,
PropTypes
} from 'react'
格式化后为
import React, {Component,PropTypes} from 'react'

**Comment by oMaten** [comment]
add this `"brace_style": "collapse-preserve-inline"` @liyangmsn

**Comment by thecotne** [comment]
we don't speak whatever that language is. sorry
