### ISSUE TITLE
php intervals

### ISSUE THREAD

**Issue by ildarkhasanshin** [akalongman/sublimetext-codeformatter#260]
is it possible to make adjustments to the alignment of the lines of php-block?

now so
![img-2016-09-11-17-17-15](https://cloud.githubusercontent.com/assets/8765305/18417249/30d4699e-784c-11e6-9173-bbe85f187df2.png)

must be so
![img-2016-09-11-17-17-53](https://cloud.githubusercontent.com/assets/8765305/18417252/3468ff20-784c-11e6-8a03-3997bba6034f.png)

`"codeformatter_php_options": {
    "syntaxes": "php", 
    "php_path": "/usr/bin/php", 
    "format_on_save": false, 
    "php55_compat": false, 
    "psr1": false, 
    "psr1_naming": false, 
    "psr2": false, 
    "indent_with_space": 2, 
    "enable_auto_align": true, 
    "visibility_order": true, 
    "smart_linebreak_after_curly": true, 
    "passes": [],
    "exclude": [ "PSR1OpenTags" ]
}`

**Comment by akalongman** [comment]
No, files with mixed languages is very difficult to format
