### ISSUE TITLE
CodeFormatter doesn't format HTML file

### ISSUE THREAD

**Issue by gusbemacbe** [akalongman/sublimetext-codeformatter#264]
Gamarjoba, Avtandil!

I installed a CodeFormatter package from Package control via Sublime Text 3. I selected Format Code and the HTML file wasn't beautified. 

Check my HTML file that wasn't beautified by CodeFormatter:
https://github.com/gusbemacbe/bootstraphyphen/blob/master/teste2.html

How to fix it?

Me var madlobeli sheni pasukhitvis!

Gustavo

**Comment by RevanProdigalKnight** [comment]
If you haven't changed your settings, it's probably using the BeatifulSoup formatter. Try adding `"formatter_version": "regexp"` to your user settings file.

**Comment by gusbemacbe** [comment]
What is the user setting file? CodeFormatter user settings file or Sublime Text user settings file?

**Comment by Scarboroid** [comment]
@gusbemacbe CodeFormatter user settings. I hope you found the answer two years ago. Can you close this issue?

**Comment by gusbemacbe** [comment]
Although the formatting worked, the style is not solved yet. For example, in a HTML file, when you format code, the tags `b`, `i` and other are indented into new lines. And non-tags also are indented into new lines.
