### ISSUE TITLE
Format error: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by riverofjanuary** [akalongman/sublimetext-codeformatter#268]
Getting this error when using the Format Code command on any file. Installed the very latest version via package control with no problems.

**Comment by mickyyman** [comment]
Exact same problem.

**Comment by jjdias** [comment]
Anyone got a solution yet?

**Comment by riverofjanuary** [comment]
Just uninstalled it. Seems like a crappy addon...

**Comment by thecotne** [comment]
@mickyyman @jjdias post os and sublime version and sublime console output

**Comment by invasoria** [comment]
I was having the same problem only while trying to format PHP code on Windows 10, Sublime Text Build 3126.

Fixed it by configuring the correct path to the PHP executable in the package settings. This line to be exact:

`
"php_path": "/your/path/goes/here", // Path for PHP executable, e.g. "/usr/lib/php" or "C:/Program Files/PHP/php.exe". If empty, uses command "php" from system environments
`

**Comment by riverofjanuary** [comment]
One of my problems was that another modal dialog was open (in my case, the nagware to buy ST3). I didn't see it, but once I closed it the command worked.

**Comment by sellmark** [comment]
@invasoria Thanks Ivan, that really works. 
You need to install PHP if you don't have one on your Windows 10.

**Comment by thecotne** [comment]
closing since it's not real issue

**Comment by gozzzart** [comment]
to all good body very careful about those trying to tell us they are part of good groups

**Comment by Orange-Moose** [comment]
Deleting JSLint package solved the problem for me.
