### ISSUE TITLE
PHP echo in html attribute fail

### ISSUE THREAD

**Issue by kozusnikjan94** [akalongman/sublimetext-codeformatter#285]
Hello,

I find out quite strange fail:
this:
`<div class="<?= 'hello' ?>">`
after formatting looks like this:
`<div class=" <?= 'hello' ?/> ">`

Is there any way how to solve it?

**Comment by akalongman** [comment]
Should be fixed via https://github.com/akalongman/sublimetext-codeformatter/issues/355#issuecomment-381722577
