### ISSUE TITLE
php and html and js mixed formate

### ISSUE THREAD

**Issue by ddbxyrj** [akalongman/sublimetext-codeformatter#295]
The plug is just great. Actually it is the main reason I use sublime as edit tool rather than IDE. However, there is a problem confuse me long time ago. Could it possible format an field which written by multiple code,let say php and html and js. 

As what I thought, the format plug or sublime itself should be  capable to recognize the language which  every block are written. I think IDE can have the ability of the recognition.
thank all your opinions.

**Comment by thecotne** [comment]
https://github.com/akalongman/sublimetext-codeformatter/issues/157#issuecomment-219801342
