### ISSUE TITLE
When code formatting PHP code

### ISSUE THREAD

**Issue by akumaburn** [akalongman/sublimetext-codeformatter#297]
It strips the last closing tag if there is only PHP code in the file and no HTML.

IE:

```
<?php

?>
```

Becomes 

`<?php`

unless i do something like

```
<?php

?>
<!--END of php-->
```

PS: sent ya a donation, check: 8N394289JL157674X paypal

**Comment by thecotne** [comment]
this is very useful feature see [PSR-2 files](http://www.php-fig.org/psr/psr-2/#files)

and it's definitely not a bug

**Comment by akumaburn** [comment]
There should be a toggle for it then, that coding style is not good PHP programming. Given that it will mess up any combination of HTML and PHP, which is the primary use case of PHP.

**Comment by akumaburn** [comment]
Nvm, should of checked the options first, there is a toggle for it!
