### ISSUE TITLE
Disable remove unused class

### ISSUE THREAD

**Issue by jericopulvera** [akalongman/sublimetext-codeformatter#313]
How do I disable the removing of unused class?

```
<?php

namespace App;

use AvSetAvailabilities;

class AvSetAccommodation
{
    
    public function handle()
    {
        // dispatch(new AvSetAvailabilities());=
    }
}

```

when I format the AvSetAvailabilities gets removed.

```
<?php

namespace App;

class AvSetAccommodation
{
    
    public function handle()
    {
        // dispatch(new AvSetAvailabilities());=
    }
}

```

how do I disable that?

**Comment by mtownsend5512** [comment]
I also want to know. This is really annoying.

**Comment by Dartui** [comment]
You should try add `OrderAndRemoveUseClauses` to `excudes` in config

**Comment by WingCH** [comment]
![2017-11-06 at 12 28](https://user-images.githubusercontent.com/19588517/32425434-1253e74a-c2ee-11e7-9d89-abd8646ce0d5.png)
