### ISSUE TITLE
PHP 7 and null coalescing

### ISSUE THREAD

**Issue by lorisleiva** [akalongman/sublimetext-codeformatter#319]
Hello,

My codestyle reformats the null coalescing operator by adding a double space between the question marks.

```php
// From.
$a = $b ?? null;

// To.
$a = $b ?  ? null;
```

I've tried to remove all transformers from phpF but this does not fix the problem.

Does anyone have an idea about how I could fix this in my configs? Or is the code formatter not supporting PHP 7?

Best,
Loris

**Comment by lorisleiva** [comment]
I've managed to make it work locally by making the package use the `fmt-php7.phar` library instead of `fmt.phar` here:

https://github.com/akalongman/sublimetext-codeformatter/blob/master/codeformatter/phpformatter.py#L80

It would be helpful to have it as an option or have it by default since you have the php55 option already.

**Comment by akalongman** [comment]
Guys, could you test version from `dev` branch?

**Comment by lorisleiva** [comment]
I haven't had any problems with that for a while now, so I it must have been fixed :) Thank you.
