### ISSUE TITLE
Code deleted after pressing ctr+alt+f

### ISSUE THREAD

**Issue by shahzadthathal** [akalongman/sublimetext-codeformatter#324]
Hi,

I'm using the latest version of sublime text editor and code-formatter, I tried to PHP code but after pressing ```ctr+alt+f``` my code deleted, it is strange.

```
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Test;

class UserController extends Controller
{
....
}
```

My code ```use App\Models\Test;```  always deleted by code formatter whenever I pressed ctr+alt+f.

**Comment by WingCH** [comment]
https://github.com/akalongman/sublimetext-codeformatter/issues/313

**Comment by thecotne** [comment]
this is not issue it is designed this way you need to set your configuration carefully
