### ISSUE TITLE
php wrong formatting for using namespace

### ISSUE THREAD

**Issue by guvi77** [akalongman/sublimetext-codeformatter#357]
Hi,

The formatter remove "use namespace".
It keeps the "use namespace" only if I use that namespace in code which is wrong, because the scope of "use namespace" is to call a class with short name (without the namespace). If I call a class with full namespace name   "use namespace"  it's useless.

So, you do not have to remove any use namespace because you do not know what classes are called with short name from namespace.

Ex: let's suppose we have a class MyClass defined in the namespace MyNamespace.
I can call the class in 2 ways:
1. using full namespace class name (in this case "use MyNamespace" is useless).
```
<?php
$c = new \MyNamespace\MyClass();
?>
```

2. using shortname:
```
<?php
use MyNamespace;
$c = new MyClass();
?>
```

In the case 2 the formatter remove use MyNamespace, which is wrong.

Thank you.

**Comment by akalongman** [comment]
Please look at https://github.com/akalongman/sublimetext-codeformatter/issues/355#issuecomment-381722577
