### ISSUE TITLE
phpF abandoned

### ISSUE THREAD

**Issue by droptable** [akalongman/sublimetext-codeformatter#360]
phpF has been abandoned:
https://github.com/subins2000/phpF/blob/master/README.md

Some new features like nullable types, "yield from", trailing commas in lists (and probably more after  PHP 7.2/3) are not supported and (i think?) will not be implemented in the near future.

The fork of MKCG looks like a good replacement (see subins2000 README):
https://github.com/MKCG/phpfmt_stable

**Comment by rjksn** [comment]
Is there another text editor that offers these functions without having to use this plugin?

**Comment by droptable** [comment]
You can replace the "fmt.phar" file in your local codeformatter installation with the fmt.phar from here:
https://github.com/phpfmt-next/fmt/tree/master/bin

**Comment by akalongman** [comment]
Please look at https://github.com/akalongman/sublimetext-codeformatter/issues/355#issuecomment-381722577

phpF will be removed soon
