### ISSUE TITLE
Error while applying formatting

### ISSUE THREAD

**Issue by pkmishra** [akalongman/sublimetext-codeformatter#4]
CodeFormatter

Format error:
[Errno 2] No such file or directory

**Comment by tiggem1993** [comment]
Installed Latest v3.1.0. But still Getting Error.

![sublime2_codeformatter error](https://cloud.githubusercontent.com/assets/16758184/12842098/7aaf3c02-cc16-11e5-92c4-9f4e56c9bcf4.jpg)

**Comment by akalongman** [comment]
Show me your CodeFormatter settings

**Comment by tiggem1993** [comment]
I am Using Sublime 2 with these setting:

![sublime2_codeformatter-settings](https://cloud.githubusercontent.com/assets/16758184/12847906/9b354b44-cc3c-11e5-9c84-2d3329f9487f.jpg)
