### ISSUE TITLE
New format for codeformatter

### ISSUE THREAD

**Issue by Thijmen** [akalongman/sublimetext-codeformatter#43]
Hi,

I am using Laravel (.blade.php) files and I'd like to format my HTML with this extension.
Now, I need to set my format to HTML and then format my code. I think it should be an easy thing to do but couldn't find it out.

Best regards

**Comment by mtpultz** [comment]
+1

**Comment by danielspringl** [comment]
I added this line:

'laravel blade highlighter' : HtmlFormatter,

to self.classmap array in formatter.py and it is working fine now. 

But it would be fine to add it in next release for everyone.

**Comment by thecotne** [comment]
will be fixed in #140

**Comment by phaberest** [comment]
Are you sure? It does not seem to work. Yet.

**Comment by thecotne** [comment]
@phaberest you can add blade in html syntaxes like this https://github.com/akalongman/sublimetext-codeformatter/commit/cb45b30ae307718e0868204d4a5b72194ba82570

in next release version this will be in default settings
