### ISSUE TITLE
CodeFormatter  Format error: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by ivinpolosony** [akalongman/sublimetext-codeformatter#54]
I am getting this error while formatting the code

**Comment by nivincp** [comment]
same issue again.

I have tried the version you have mentioned in the above link but I couldn't see psr2 configs in that.

could you please let me know how can we fix it in the new version?

**Comment by akalongman** [comment]
Copy default settings in your CodeFormatter user settings file. This must work

**Comment by nivincp** [comment]
I tried that but still the same issue.

**Comment by geo4orce** [comment]
same problem. Tried everything from above, all permissions are set, everything is up-to-date.

Please advise.

**Comment by ivanzhujunwei** [comment]
I resolved the "Permission denied" error, but when I formatted the php code, nothing happened, the code was still in a clutter.

**Comment by coscho** [comment]
I recently installed on a system with php 7.0 

php path is this.

```
$ which php
/usr/bin/php
```

php_path is setup correctly :
`php_path": "/usr/bin/php",`

I assumed I need to run the command pr php 7 ... right ?
 
`sudo chmod +x /home/clara/.config/sublime-text-3/Packages/CodeFormatter/codeformatter/lib/phpbeautifier/fmt-php7.phar`

If all that are correctly .. what am I doing wrong ?
