### ISSUE TITLE
php_beautifier [error] Can't match any file

### ISSUE THREAD

**Issue by macgile** [akalongman/sublimetext-codeformatter#59]
Hi all,
I have this error in SBT3
php_beautifier [error] Can't match any file

Regards

macgile

**Comment by thecotne** [comment]
is this solved?

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
