### ISSUE TITLE
Twig files

### ISSUE THREAD

**Issue by i-bajrai** [akalongman/sublimetext-codeformatter#60]
Is there a way to make the package emulate the formatting for HTML into TWIG files?

**Comment by cigzigwon** [comment]
if you pult ur sublime syntax to html it will do a better job than nothing but isnt perfect

**Comment by thecotne** [comment]
like this you can add any syntax in any formatter 

https://github.com/akalongman/sublimetext-codeformatter/issues/43#issuecomment-194387767
