### ISSUE TITLE
HTML Formatting not working with javascript inside comments tags. 

### ISSUE THREAD

**Issue by noducks** [akalongman/sublimetext-codeformatter#61]
If I code-format a html file like this with shift-ctrl-F (on a mac) a number of times. 

    <html>
    <head>
    </head>
    <body>
        
    </body>
    </html>

I'll end up with this.. 

    <html>
    <head>
    </head>
    <body>
        
        </body>
    </html>

which will eventually look very bad in sublime, with a single line using up many lines  similar to the attached image.

![screen shot 2014-02-24 at 20 46 54](https://f.cloud.github.com/assets/3964334/2250872/28775e8a-9d95-11e3-8cb1-0d3ab3344c77.png)

**Comment by thecotne** [comment]
this is fixed 
@noducks ping me to re open this issue if needed
