### ISSUE TITLE
PHP - Space Between parentheses and brackets?

### ISSUE THREAD

**Issue by dovy** [akalongman/sublimetext-codeformatter#63]
I saw this wonder online PHP formatter has one attribute I really wish codeformatter would integrate.

http://beta.phpformatter.com/

Namely:
### Brackets
* Space inside brackets - ( )
* Space inside empty brackets - ( )
* Space inside block brackets - [ ]
* Space inside empty block brackets - [ ]

Any chance of getting that added?

**Comment by mtpultz** [comment]
+1

**Comment by RyanGannon** [comment]
+1

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)

**Comment by ecreatrix** [comment]
Sorry but I can't see how version 3.0.0 solved this issue. Is there a setting for PHP that's similar to the JS setting "space_in_paren"?

**Comment by lbngoc** [comment]
CodeFormatter change to use phpfmt to format PHP file.
I have just check on fmt github and see that it is not have a transformation for this. :(

**Comment by saltnpixels** [comment]
+1

**Comment by xttn** [comment]
+1
