### ISSUE TITLE
Arrays formatting

### ISSUE THREAD

**Issue by MattDalm** [akalongman/sublimetext-codeformatter#64]
New array notation does not get formatted correctly. 
Expected format is

<?php
$array = array(
    "foo" => "bar",
    "bar" => "foo",
);

// as of PHP 5.4
$array = [
    "foo" => "bar",
    "bar" => "foo",
];
?>

Here is what I get :
$array = [ "foo" => "bar", "bar" => "foo",];

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
