### ISSUE TITLE
Formatting Trait

### ISSUE THREAD

**Issue by gambledor** [akalongman/sublimetext-codeformatter#66]
In SublimeText 2 with plugin version 2.3.0 I've got the following error

CodeFormatter 
Format error:
 php_beautifier [error] Token  doesn't exists

**Comment by Exadra37** [comment]
Hi same error here:

![screenshot from 2015-03-31 17 21 21](https://cloud.githubusercontent.com/assets/1745456/6923565/695d0b5a-d7ca-11e4-9c33-c91af68dc697.png)


![screenshot from 2015-03-31 17 20 31](https://cloud.githubusercontent.com/assets/1745456/6923537/51c7de16-d7ca-11e4-938f-c12e185a7d6b.png)


I have installed first with Package Control and after with git clone and restarted Sublime in both times and still have the issue.

Do you need any more info?

**Comment by thecotne** [comment]
works for me 

@Exadra37 i need php file (gist)

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
