### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by hirehead** [akalongman/sublimetext-codeformatter#68]
Hi. Could you please add typescript support, which will require two changes.
1) "=>" sign. Get latest of the js-beautifier, this issue was fixed https://github.com/einars/js-beautify/blob/master/python/jsbeautifier/__init__.py#L261 in comparison to the one in the codeformatter's lib: https://github.com/akalongman/sublimetext-codeformatter/blob/master/codeformatter/lib/jsbeautifier/__init__.py#L259 Pay attention to the very last sign.
2) Add new formatter 'typescript': JsFormatter, next to https://github.com/akalongman/sublimetext-codeformatter/blob/master/codeformatter/formatter.py#L36

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)

**Comment by shaneparsons** [comment]
Just to add to this, dedicated typescript options (rather than sharing js options) would be great for things like import statements, where newlines after braces are not wanted.

i.e. `import { Component } from '@angular/core';`
