### ISSUE TITLE
Support for Unicode in Javascript

### ISSUE THREAD

**Issue by mphasize** [akalongman/sublimetext-codeformatter#73]
Hi, 

I just had a problem, that the JS code formatter wouldn't work with Unicode characters in strings.  I tried it on this example code: http://www.nodemailer.com/docs/usage-example and the formatter simply didn't work. 

Unfortunately I don't know if this problem is related to the Sublime package or the underlying JS Beautifier. Any ideas?

Cheers!
Marcus

**Comment by walane** [comment]
Hi,

Thanks for the fix but that's not a solution at all, especially if you must use utf8 strings in your code.
A fix is it planned ?

Thank you for your work.

**Comment by thecotne** [comment]
i can't reproduce
i need example file (gist)

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
