### ISSUE TITLE
JS preserve json alignment 

### ISSUE THREAD

**Issue by rleger** [akalongman/sublimetext-codeformatter#74]
Hi,

First off, GREAT package !! thank you for this :)

A small request, I have a lot of mapping happening in my javascript on a particular project and I would like it to align it as shown below, or at least keep it aligned like I did when I reformat.

I use Alignment plugin to do that, which is great, but it gets messed up every time I reformat my code.

I tried : 
```
"keep_array_indentation": true
```
 but it didn't change anything...

If you have a suggestion or a way to fix this it would be super cool.

Thanks again.

Romain

```
ObjectLibraryMappedJson = $.map( data, function( ObjectLibrary, index ) {
                return {
                    object_id   : ObjectLibrary.object_id,
                    name        : ObjectLibrary.name,
                    description : ObjectLibrary.description,
                    notes       : ObjectLibrary.notes,
                    price_client: ObjectLibrary.price_client,
                    price_pro   : ObjectLibrary.price_pro,
                    dim_length  : ObjectLibrary.dim_length,
```

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
