### ISSUE TITLE
Don't newline PHP inside of HTML

### ISSUE THREAD

**Issue by chriscct7** [akalongman/sublimetext-codeformatter#75]
When you have something like this in a file you're formatting:
`<div><?php echo 'something'; ?></div>` 
it currently make it
`<div><?php
echo 'something';
?></div>`

Which is super annoying. There should be a way to turn off newlining PHP inside of HTML

**Comment by natepizzle** [comment]
Yeah, It would be nice if there was a setting to remove excess newlines
```PHP
public function __construct() {
                
                $this->pop_conn = 0;
                
                $this->connected = false;
                
                $this->error = null;
        }
```

**Comment by ccirello** [comment]
@natepizzle report the need of this feature into phpfmt/fmt - we'll check over there whether it can be arranged.
