### ISSUE TITLE
PHP variable with curly syntax

### ISSUE THREAD

**Issue by damien-list** [akalongman/sublimetext-codeformatter#77]
Hello,

I have curly variables in my php code like :

${'foo'}

which are becoming once formatted :

$ {
'test'
}

It seems that these vars are beeing formatted like a if statement.

Is it possible you can look into it ?
Thanks for your help.

**Comment by resuly** [comment]
+1

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
