### ISSUE TITLE
Working with XAMPPLITE ?

### ISSUE THREAD

**Issue by alemanne** [akalongman/sublimetext-codeformatter#78]
Hi,

I've set up your plugin and it works fine in HTML Code.

Win 8.0 and ST3, Plugin Vers. 2.4.0

And I get an Errormessage:

---------------------------
Sublime Text
---------------------------
CodeFormatter

Format error:
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampplite\php\ext\php_gd2.dll' - Das angegebene Modul wurde nicht gefunden.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampplite\php\ext\php_gettext.dll' - Das angegebene Modul wurde nicht gefunden.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampplite\php\ext\php_imap.dll' - Das angegebene Modul wurde nicht gefunden.
 in Unknown on line 0

... and many lines more with information of Modules, that cannot be found.

So, can it be, that the plugin doesn't work with XXAMP? 

And: What can I do to fix that Error?

Best regards, Tom

**Comment by thecotne** [comment]
@alemanne you need to add php in PATH or modify package settings to include path to php installation
 https://github.com/akalongman/sublimetext-codeformatter/blob/master/CodeFormatter.sublime-settings#L3
