### ISSUE TITLE
New line after if() without braces (PHP)

### ISSUE THREAD

**Issue by scottfriebel** [akalongman/sublimetext-codeformatter#79]
Would it be possible to add/preserve new lines after an if() statement that doesn't have braces (i.e. single line if statements)
If not, just adding the preserve_newlines parameter like the javascript settings has would help.

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
