### ISSUE TITLE
CodeFormatter  Format error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by aaronpeterson** [akalongman/sublimetext-codeformatter#82]
I have found previous issues posted about this error but with no working solution.

```
CodeFormatter

Format error:
[Errno 2] No such file or directory
```

I receive this upon attempting to format a .php file.  Some info about this machine:

OSX 10.8.4
Sublime 2.0.2 build 2221

```
which php_beautifier
/opt/local/bin/php_beautifier

php_beautifier --version
(a bunch of PHP Strict standards notices)
PHP_Beautifier 0.1.15

which node
/opt/local/bin/node

which php
/opt/local/bin/php

php --version
PHP 5.4.24 (cli) (built: Jan 10 2014 17:09:49)

node --version
v0.10.25
```

I have tried removing the CodeFormatter and reinstalling via Package Control as well as installing via git clone; the problem remains persistent across installation methods.

I hope this is of use to someone.  Still trying to nail down the root of the problem.

**Comment by sandy1890** [comment]
I got the same probleme.
When i view the phpbeautifier file in:
 ~/.config/sublime-text-3/Packages/CodeFormatter/codeformatter/lib/phpbeautifier

I saw the firet line:

#!/usr/bin/php -Cq

Becaust my php isn't install in the "/usr/bin/php" path, so i do this:

sudo ln -s /usr/bin/php /usr/local/php/5.3.28/bin/php

And it's work now.

**Comment by akalongman** [comment]
You can define php path manually in settings

**Comment by oscarvesga** [comment]
Hi, I have the same problem, this is the output of my console
```
Format error:
[WinError 2] El sistema no puede encontrar el archivo especificado
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Unable to open /C/Users/o-vesga/AppData/Roaming/Sublime Text 3/Packages/Default/Default (Windows).sublime-keymap
```

**Comment by musasoftlabx** [comment]
For those using XAMPP on windows, change path from

**From**
"codeformatter_php_options":
    {
        "syntaxes": "php",
        "php_path": "",
        "format_on_save": true,

**To** 
"codeformatter_php_options":
    {
        "syntaxes": "php",
        "php_path": "C:/XAMP/php/php-win.exe",
        "format_on_save": true,
