### ISSUE TITLE
Incorrect spacing for EcmaSCRIPT 6 arrow functions

### ISSUE THREAD

**Issue by breandr** [akalongman/sublimetext-codeformatter#85]
A space is added between `=` and `>` when trying to use the new arrow functions (`=>`) in ES 6/Next/Harmony.

**Comment by billrawlinson** [comment]
This would be a nice one to get fixed. We basically can't use this extension at this time due to this issue (and one other).

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)

**Comment by billrawlinson** [comment]
that does look better; thanks
