### ISSUE TITLE
missing support for some filetypes

### ISSUE THREAD

**Issue by maegain** [akalongman/sublimetext-codeformatter#87]
iam relly missing support for certain filetypes, like cshtml, aspx, ascx, and asp

Can you like force lets say .asp page to use html as formatter?

html dosent really work when your doing html-templates under  script-element
<script type="text/html">

</script>

otherwise love the extension good work!

**Comment by thecotne** [comment]
like this you can add any syntax in any formatter 

https://github.com/akalongman/sublimetext-codeformatter/issues/43#issuecomment-194387767
