### ISSUE TITLE
Incorrect format javascript source code - chaining methods

### ISSUE THREAD

**Issue by theking-laptop** [akalongman/sublimetext-codeformatter#89]
Suppose I have a snippet:
```
abc
.hello()
.hi();
```
Then format output:
```
abc
	.hello()
	.hi();
```
It's correct. But if I add an empty line or a comment line before `hello` or `hi` method, the format output is incorrect.
Input and output are the same:
```
abc

.hello()
// say "hi"
.hi();
```

**Comment by akalongman** [comment]
Fixed in 1.6.1 version
