### ISSUE TITLE
equals_align should be ignored on functions

### ISSUE THREAD

**Issue by lordn-n** [akalongman/sublimetext-codeformatter#90]
For example:

    $this->forward404Unless($recurso = RecursoPeer::retrieveByPk($request->getParameter('id')));
    $this->form=new recursoForm($recurso);
    $this->detalle=RecursoPeer::listaRecursos();

Is formatted like this:

    $this->forward404Unless($recurso       = RecursoPeer::retrieveByPk($request->getParameter('id')));
    $this->form    = new recursoForm($recurso);
    $this->detalle = RecursoPeer::listaRecursos();

Can you see how the variable inside the function is also aligned? `$recurso       = `
The equals_align should be ignored inside functions.

**Comment by sunxch100** [comment]
Very Good,This should be corrected.

**Comment by akalongman** [comment]
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)
