### ISSUE TITLE
PHP switch indentation

### ISSUE THREAD

**Issue by qooob** [akalongman/sublimetext-codeformatter#95]
Performing PHP in _allman_ and _GNU_ styles indentation should also be applied to switch:

Now:
```
switch ($i) 
{
case 0:
  echo "i равно 0";
break;
case 1:
  echo "i равно 1";
break;
case 2:
  echo "i равно 2";
break;
}
```

Should be:
```
switch ($i)
{
    case 0:
        echo "i равно 0";
        break;
    case 1:
        echo "i равно 1";
        break;
    case 2:
        echo "i равно 2";
        break;
}
```

Could you please fix it?

**Comment by mtpultz** [comment]
+1

**Comment by mtpultz** [comment]
@qooob there's a [patch](http://pear.php.net/bugs/bug.php?id=10019&edit=11) that you can drop into PHP_Beautifier, or you can wait for PR #122.
