### ISSUE TITLE
[Linux ST2] Does absolutely nothing with "new file", error message on open file.

### ISSUE THREAD

**Issue by mmazing** [akalongman/sublimetext-codeformatter#96]
On Sublime Text 2, when copying and pasting some HTML code into a new file, using CTRL-SHIFT-P and selecting Format Code does nothing with no messages.
CTRL-ALT-F yields the same results.

Opening a PHP file and using CTRL-ALT-F yields the error message "[Errno 2] No such file or directory".

Has this been tested in a linux environment?

**Comment by BarbzYHOOL** [comment]
same exact error for me
