### ISSUE TITLE
Treat handlebars files *.hbs as html

### ISSUE THREAD

**Issue by numediaweb** [akalongman/sublimetext-codeformatter#97]
Handlebars is basically HTML, how can I make SCF treat *.hbs as html? 
Currently getting:
:x: Formatter for this file type (handlebars) not found.

I'm using [daaain/Handlebars](https://github.com/daaain/Handlebars) Sublime 3 package.

**Comment by thecotne** [comment]
there is syntaxes option implemented and will be in next release 
https://github.com/akalongman/sublimetext-codeformatter/blob/master/CodeFormatter.sublime-settings#L71
